steps:
  # 1. Встановлення залежностей
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # 2. Білдування продуктивної версії додатку
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - 'API_KEY=${_GEMINI_API_KEY}'
      - 'VITE_API_KEY=${_GEMINI_API_KEY}'

  # 3. Білдування Docker образу для Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/smileafterburn-social-map:latest'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/smileafterburn-social-map:${SHORT_SHA}'
      - '.'
    env:
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'

  # 4. Push Docker образу в Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/smileafterburn-social-map'

  # 5. Розгортання на Cloud Run
  - name: 'gcr.io/cloud-builders/run'
    args:
      - 'deploy'
      - 'smileafterburn-social-map'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/smileafterburn-social-map:${SHORT_SHA}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/${PROJECT_ID}/smileafterburn-social-map:latest'
  - 'gcr.io/${PROJECT_ID}/smileafterburn-social-map:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GEMINI_API_KEY: 'AIzaSyAR9B8YtLNCe2bagT9SD1lM2bcPnBkkZbg'
  _PROJECT_NUMBER: '625307458804'
