
steps:
  # 1. Встановлення залежностей
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # 2. Збірка продуктивної версії додатку
  # Ми передаємо API_KEY як змінну середовища для процесу збірки, 
  # якщо ваш код очікує її під час компіляції (наприклад, для Vite)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'API_KEY=${_API_KEY}'

# 3. Визначення артефактів (результатів збірки)
# Після завершення файли з папки 'dist' будуть завантажені у ваш GCS бакет
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET}/builds/$BUILD_ID'
    paths: ['dist/**']

# Налаштування логування та змінних за замовчуванням
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _API_KEY: 'placeholder-key' # Можна перевизначити через gcloud або тригери
  _ARTIFACT_BUCKET: 'your-gcs-bucket-name' # Вкажіть ім'я вашого бакета
