import { Organization, RegionName } from './types';

export const SHEET_URL = 'https://docs.google.com/spreadsheets/d/1ev98ifed1h8xc16KcWaOmvaky8I9StuE0-6w7UPG4K4/edit?gid=1212063265#gid=1212063265';
export const DRIVE_URL = 'https://drive.google.com/drive/folders/1kSQKI_-2b8mmWfUw5ZHvGaDD9g4tPWqU?usp=sharing';
export const REFERRAL_DRIVE_URL = 'https://drive.google.com/drive/folders/1cBKp3HoTfujq8AamTKK37HjtHC59GHyt?usp=sharing';

export const REGION_CONFIG: Record<RegionName, { center: [number, number], zoom: number, label: string }> = {
  'Odesa': {
    center: [46.4825, 30.7233],
    zoom: 12,
    label: 'Одеська область'
  },
  'Mykolaiv': {
    center: [46.9750, 31.9946],
    zoom: 12,
    label: 'Миколаївська область'
  },
  'Kherson': {
    center: [46.6354, 32.6169],
    zoom: 12,
    label: 'Херсонська область'
  },
  'Dnipro': {
    center: [48.4647, 35.0462],
    zoom: 11,
    label: 'Дніпропетровська область'
  },
  'Zaporizhzhia': {
    center: [47.8388, 35.1396],
    zoom: 11,
    label: 'Запорізька область'
  }
};

// Дані для Одеської, Миколаївської, Херсонської, Дніпропетровської та Запорізької областей
export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: '1',
    name: 'БФ "Корпорація Монстрів"',
    address: 'вул. Пантелеймонівська, 21, Одеса',
    lat: 46.4694,
    lng: 30.7404,
    category: 'Благодійний фонд',
    services: 'Гуманітарна допомога, медичне забезпечення лікарень, допомога ВПО, адресна допомога дітям.',
    phone: '+380 99 123 4567',
    email: 'info@monsters.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 25000000,
    region: 'Odesa'
  },
  {
    id: '2',
    name: 'Гуманітарний штаб "Миколаїв"',
    address: 'вул. Нікольська, 25, Миколаїв',
    lat: 46.9750,
    lng: 31.9946,
    category: 'Волонтерський штаб',
    services: 'Роздача продуктових наборів, забезпечення питною водою, евакуація населення.',
    phone: '+380 63 987 6543',
    email: 'help@mykolaiv.volunteer',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 12500000,
    region: 'Mykolaiv'
  },
  {
    id: '3',
    name: 'Херсонський Хаб "Я - Херсон"',
    address: 'пл. Свободи, 1, Херсон',
    lat: 46.6354,
    lng: 32.6169,
    category: 'Громадська організація',
    services: 'Психологічна підтримка, юридичні консультації, відновлення документів, шелтер.',
    phone: '+380 50 555 0101',
    email: 'support@kherson.hub',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 8100000,
    region: 'Kherson'
  },
  {
    id: '4',
    name: 'Карітас Одеса УГКЦ',
    address: 'вул. Південна, 40, Одеса',
    lat: 46.4580,
    lng: 30.7100,
    category: 'Релігійна місія',
    services: 'Догляд вдома, робота з дітьми та молоддю, кризовий центр, гуманітарна допомога.',
    phone: '+380 48 777 8899',
    email: 'caritas@odessa.ugcc',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 18000000,
    region: 'Odesa'
  },
  {
    id: '5',
    name: 'Червоний Хрест Миколаївщини',
    address: 'пр. Центральний, 12, Миколаїв',
    lat: 46.9660,
    lng: 32.0000,
    category: 'Міжнародна організація',
    services: 'Навчання першій допомозі, видача ваучерів, підтримка літніх людей.',
    phone: '+380 512 34 56 78',
    email: 'mk@redcross.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 30000000,
    region: 'Mykolaiv'
  },
  {
    id: '6',
    name: 'Волонтерський центр "Корабельний"',
    address: 'Корабельний район, Херсон',
    lat: 46.6100,
    lng: 32.5800,
    category: 'Волонтерський пункт',
    services: 'Гаряче харчування, пункти обігріву, допомога з будматеріалами.',
    phone: '+380 66 222 3344',
    email: 'korabelny@volunteer.ks',
    status: 'Pending',
    driveFolderUrl: DRIVE_URL,
    budget: 950000,
    region: 'Kherson'
  },
  {
    id: '7',
    name: 'БФ "ПОСМІШКА ЮА" (Одеса)',
    address: 'м. Одеса, Одеська область',
    lat: 46.4825,
    lng: 30.7233,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Odesa'
  },
  {
    id: '8',
    name: 'БФ "ПОСМІШКА ЮА" (Миколаїв)',
    address: 'м. Миколаїв, Миколаївська область',
    lat: 46.9600,
    lng: 32.0100,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Mykolaiv'
  },
  {
    id: '9',
    name: 'БФ "ПОСМІШКА ЮА" (Херсон)',
    address: 'м. Херсон, Херсонська область',
    lat: 46.6400,
    lng: 32.6100,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Kherson'
  },
  {
    id: '10',
    name: 'ВТК «Феникс-Медикал»',
    address: 'м. Одеса',
    lat: 46.4750,
    lng: 30.7450,
    category: 'Компанія',
    services: 'Люди з інвалідністю (ТЗР)',
    phone: '+38 (067) 488-76-00',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '11',
    name: 'Благодійний фонд «Ассалам»',
    address: 'м. Одеса',
    lat: 46.4850,
    lng: 30.7150,
    category: 'Благодійний фонд',
    services: 'Переселенці; біженці',
    phone: '+38 (048) 780-13-04',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '12',
    name: 'Благодійний фонд «Подсолнух»',
    address: 'м. Одеса',
    lat: 46.4650,
    lng: 30.7350,
    category: 'Благодійний фонд',
    services: 'Діти з ОРА; діти-інваліди',
    phone: '+38 (048) 799-33-05',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '13',
    name: 'Благодійний фонд «Жива Надежда»',
    address: 'м. Одеса',
    lat: 46.4550,
    lng: 30.7250,
    category: 'Благодійний фонд',
    services: 'Діти/підлітки з малозабезпечених сімей',
    phone: '+38 (048) 787-47-98',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '14',
    name: 'БФ "Дорога до будинку" (Way Home)',
    address: 'м. Одеса',
    lat: 46.4715,
    lng: 30.7350,
    category: 'Благодійний фонд',
    services: 'Соціальна адаптація, робота з безпритульними, реабілітація',
    phone: '+38 (048) 777-20-76',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 5000000,
    region: 'Odesa'
  },
  {
    id: '15',
    name: 'БО "СІМ`Я" - "Територія Дітей"',
    address: 'м. Одеса',
    lat: 46.4600,
    lng: 30.7200,
    category: 'Благодійний фонд',
    services: 'Допомога сім\'ям, дітям, психологічна підтримка',
    phone: '+38 095-009-20-30',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '16',
    name: 'Притулок для жінок',
    address: 'м. Одеса',
    lat: 46.4900,
    lng: 30.7100,
    category: 'Комунальна установа',
    services: 'Притулок для жінок (при міському центрі соц. служб)',
    phone: '(048) 753-11-94',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '17',
    name: 'ТЦСО Приморського району',
    address: 'м. Одеса, Приморський р-н',
    lat: 46.4500,
    lng: 30.7500,
    category: 'Комунальна установа',
    services: 'Соціальне обслуговування пенсіонерів та вразливих груп',
    phone: '(048) 740-75-24',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '18',
    name: 'ТЦСО Пересипського району',
    address: 'м. Одеса, Пересипський р-н',
    lat: 46.5300,
    lng: 30.7600,
    category: 'Комунальна установа',
    services: 'Соціальне обслуговування, допомога вдома',
    phone: '(048) 763-03-60',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '19',
    name: 'Денний центр та Кризова кімната',
    address: 'Авангардівська громада',
    lat: 46.4800,
    lng: 30.6500,
    category: 'Комунальна установа',
    services: 'Допомога постраждалим від насильства, кризова кімната',
    phone: '+38 063-216-32-74',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '20',
    name: 'Мобільна бригада СПД',
    address: 'м. Білгород-Дністровський',
    lat: 46.1900,
    lng: 30.3500,
    category: 'Комунальна установа',
    services: 'Соціально-психологічна допомога',
    phone: '+38 063-216-29-48',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '21',
    name: 'Благодійний фонд "Щедрик"',
    address: 'м. Миколаїв',
    lat: 46.9650,
    lng: 32.0150,
    category: 'Благодійний фонд',
    services: 'Гуманітарна допомога, підтримка дітей та родин',
    phone: '0800-33-78-45',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '22',
    name: 'Благодійна організація "Ласка"',
    address: 'м. Миколаїв',
    lat: 46.9550,
    lng: 32.0250,
    category: 'Благодійний фонд',
    services: 'Благодійна допомога',
    phone: '+38 067-137-05-05',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '23',
    name: 'БФ "СОС Дитячі Містечка"',
    address: 'м. Миколаїв',
    lat: 46.9700,
    lng: 31.9800,
    category: 'Благодійний фонд',
    services: 'Допомога сім\'ям, дітям-сиротам',
    phone: '+38 063-366-23-91',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '24',
    name: 'Обласний центр соціальних служб',
    address: 'м. Миколаїв',
    lat: 46.9800,
    lng: 31.9900,
    category: 'Комунальна установа',
    services: 'Координація соціальних послуг області',
    phone: '(0512) 37-64-92',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '25',
    name: 'КУ "Центр надання соціальних послуг"',
    address: 'м. Миколаїв',
    lat: 46.9400,
    lng: 32.0000,
    category: 'Комунальна установа',
    services: 'Надання соціальних послуг населенню',
    phone: '(03241) 52-2-58',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '26',
    name: 'ТЦСО Первомайської громади',
    address: 'м. Первомайськ',
    lat: 48.0400,
    lng: 30.8500,
    category: 'Комунальна установа',
    services: 'Соціальне обслуговування громади',
    phone: '(05161) 7-51-95',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '27',
    name: 'КЗ "Вознесенський ЦНСП"',
    address: 'м. Вознесенськ',
    lat: 47.5600,
    lng: 31.3300,
    category: 'Комунальна установа',
    services: 'Центр надання соціальних послуг',
    phone: '(05134) 3-26-50',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '28',
    name: 'ХОБФ "Об\'єднання"',
    address: 'м. Херсон',
    lat: 46.6450,
    lng: 32.6250,
    category: 'Благодійний фонд',
    services: 'Гуманітарна та соціальна допомога',
    phone: '+38 098-117-56-79',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '29',
    name: 'Благодійний фонд "Я – Херсон"',
    address: 'м. Херсон',
    lat: 46.6380,
    lng: 32.6120,
    category: 'Благодійний фонд',
    services: 'Всебічна допомога мешканцям Херсона',
    phone: '0800-33-94-74',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '30',
    name: 'Херсонський обласний фонд милосердя',
    address: 'м. Херсон',
    lat: 46.6300,
    lng: 32.6000,
    category: 'Благодійний фонд',
    services: 'Милосердя та здоров\'я',
    phone: '(0552) 26-50-39',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '31',
    name: 'ТЦСО Суворовського району',
    address: 'м. Херсон, Суворовський р-н',
    lat: 46.6500,
    lng: 32.6300,
    category: 'Комунальна установа',
    services: 'Територіальний центр соціального обслуговування',
    phone: '(0552) 22-97-34',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '32',
    name: 'КЗ "Нововоронцовський ЦНСП"',
    address: 'смт Нововоронцовка',
    lat: 47.3300,
    lng: 33.9100,
    category: 'Комунальна установа',
    services: 'Соціальні послуги для населення',
    phone: '(05134) 3-26-50',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  // --- Нові регіони (Дніпро, Запоріжжя) ---
  {
    id: '33',
    name: 'БФ "ПОСМІШКА ЮА" (Дніпро)',
    address: 'м. Дніпро, Дніпропетровська область',
    lat: 48.4647,
    lng: 35.0462,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Dnipro'
  },
  {
    id: '34',
    name: 'БФ "ПОСМІШКА ЮА" (Запоріжжя)',
    address: 'м. Запоріжжя, Запорізька область',
    lat: 47.8388,
    lng: 35.1396,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Zaporizhzhia'
  },
  {
    id: '35',
    name: 'Шелтер переселенців (Дніпро)',
    address: 'м. Дніпро',
    lat: 48.4700,
    lng: 35.0500,
    category: 'Притулок',
    services: 'Тимчасове проживання для ВПО',
    phone: '+380 50 111 2233',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 500000,
    region: 'Dnipro'
  }
  // Вставте сюди нових акторів, коли користувач надасть текст
];