import { Organization, RegionName, RemoteSupportActor } from './types';

export const SHEET_URL = 'https://docs.google.com/spreadsheets/d/1ev98ifed1h8xc16KcWaOmvaky8I9StuE0-6w7UPG4K4/edit?gid=1212063265#gid=1212063265';
export const DRIVE_URL = 'https://drive.google.com/drive/folders/1kSQKI_-2b8mmWfUw5ZHvGaDD9g4tPWqU?usp=sharing';
export const REFERRAL_DRIVE_URL = 'https://drive.google.com/drive/folders/1cBKp3HoTfujq8AamTKK37HjtHC59GHyt?usp=sharing';

export const REGION_CONFIG: Record<RegionName, { center: [number, number], zoom: number, label: string }> = {
  'Odesa': {
    center: [46.4825, 30.7233],
    zoom: 12,
    label: 'Одеська область'
  },
  'Mykolaiv': {
    center: [46.9750, 31.9946],
    zoom: 12,
    label: 'Миколаївська область'
  },
  'Kherson': {
    center: [46.6354, 32.6169],
    zoom: 12,
    label: 'Херсонська область'
  },
  'Dnipro': {
    center: [48.4647, 35.0462],
    zoom: 11,
    label: 'Дніпропетровська область'
  },
  'Zaporizhzhia': {
    center: [47.8388, 35.1396],
    zoom: 11,
    label: 'Запорізька область'
  }
};

// --- Дані для Дистанційної підтримки ---
export const REMOTE_SUPPORT_ACTORS: RemoteSupportActor[] = [
  {
    id: 'r1',
    name: 'Урядова гаряча лінія',
    category: 'Державні гарячі лінії',
    phones: ['1545'],
    description: 'Цілодобова урядова гаряча лінія з усіх питань.',
    website: 'https://ukc.gov.ua/'
  },
  {
    id: 'r_dv_1',
    name: 'Гаряча лінія протидії насильству',
    category: 'Соціальний захист',
    phones: ['1547'],
    description: 'Гаряча лінія з питань протидії торгівлі людьми, запобігання та протидії домашньому насильству. Безкоштовно, анонімно.',
    website: 'https://1547.ukc.gov.ua'
  },
  {
    id: 'r_dv_2',
    name: 'Онлайн-платформа «Аврора»',
    category: 'Психологічна підтримка',
    phones: [],
    description: 'Спеціалізована психотерапевтична підтримка особам, які зазнали насильства, пов’язаного з війною (зокрема, сексуального).',
    website: 'https://avrora-help.org.ua'
  },
  {
    id: 'r_health_1',
    name: 'Лінія здоров’я жінки',
    category: 'Охорона здоров\'я',
    phones: ['3033'],
    description: 'Лінія сексуально-репродуктивного здоров’я. Первинні консультації профільного фахівця. Щодня 9:00-18:00.',
  },
  {
    id: 'r2',
    name: 'Гаряча лінія Мінреінтеграції',
    category: 'Державні гарячі лінії',
    phones: ['1548', '+380960788433'],
    description: 'Питання ВПО, евакуації та гуманітарної допомоги.',
    website: 'https://minre.gov.ua/'
  },
  {
    id: 'r3',
    name: 'Безоплатна правова допомога',
    category: 'Юридична допомога',
    phones: ['0 800 213 103'],
    description: 'Консультації юристів, допомога в оформленні документів.',
    website: 'https://legalaid.gov.ua/'
  },
  {
    id: 'r4',
    name: 'Національна лінія психологічної підтримки',
    category: 'Психологічна підтримка',
    phones: ['0 800 100 102'],
    description: 'Безкоштовна та анонімна психологічна допомога.'
  },
  {
    id: 'r5',
    name: 'Гаряча лінія запобігання домашньому насильству',
    category: 'Соціальний захист',
    phones: ['116 123', '0 800 500 335'],
    description: 'Цілодобова підтримка постраждалих від насильства (La Strada).'
  },
  {
    id: 'r6',
    name: 'Юридичний порадник для ВПО',
    category: 'Юридична допомога',
    phones: [], 
    description: 'Чат-бот та онлайн ресурси для переселенців (Viber, Telegram, Facebook).',
    website: 'https://chatbot.r2p.org.ua/'
  },
  {
    id: 'r7',
    name: 'Лінія підтримки дітей та молоді (La Strada)',
    category: 'Психологічна підтримка',
    phones: ['116 111', '0 800 500 225'],
    description: 'Консультації для дітей, підлітків та батьків. Анонімно.',
    website: 'https://la-strada.org.ua/'
  },
  {
    id: 'r8',
    name: 'Національна гаряча лінія з питань ВІЛ/СНІД',
    category: 'Охорона здоров\'я',
    phones: ['0 800 500 451'],
    description: 'Цілодобова, безкоштовна та анонімна інформаційна підтримка.'
  },
  {
    id: 'r9',
    name: 'Lifeline Ukraine',
    category: 'Психологічна підтримка',
    phones: ['7333'],
    description: 'Національна лінія з питань профілактики самогубств та підтримки психічного здоров’я.',
    website: 'https://lifelineukraine.com/get-help'
  },
  {
    id: 'r10',
    name: 'Офіс Омбудсмана України',
    category: 'Права людини',
    phones: ['0 800 50 17 20', '044 299 74 08'],
    description: 'Гаряча лінія Уповноваженого ВРУ з прав людини. Розшук зниклих, права дітей, обмін полоненими.',
    website: 'https://ombudsman.gov.ua/'
  },
  {
    id: 'r11',
    name: 'Український ветеранський фонд',
    category: 'Психологічна підтримка',
    phones: ['0 800 33 20 29'],
    description: 'Гаряча лінія кризової підтримки для ветеранів та їхніх родин (цілодобово).',
    website: 'https://veteranfund.com.ua/'
  },
  {
    id: 'r12',
    name: 'Донбас SOS',
    category: 'Допомога ВПО',
    phones: ['0 800 309 110'],
    description: 'Інформаційна підтримка ВПО, юридичні питання, перетин лінії розмежування.',
    website: 'https://www.donbasssos.org/'
  },
  {
    id: 'r13',
    name: 'Helping to Leave',
    category: 'Евакуація',
    phones: ['(093) 177 64 58'],
    description: 'Допомога з евакуацією з зон бойових дій та окупованих територій.',
    website: 'https://helpingtoleave.org/ua'
  }
];

// Дані для Одеської, Миколаївської, Херсонської, Дніпропетровської та Запорізької областей
export const INITIAL_ORGANIZATIONS: Organization[] = [
  // --- EXISTING DATA ---
  {
    id: '1',
    name: 'БФ "Корпорація Монстрів"',
    address: 'вул. Пантелеймонівська, 21, Одеса',
    lat: 46.4694,
    lng: 30.7404,
    category: 'Благодійний фонд',
    services: 'Гуманітарна допомога, медичне забезпечення лікарень, допомога ВПО, адресна допомога дітям.',
    phone: '+380 99 123 4567',
    email: 'info@monsters.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 25000000,
    region: 'Odesa'
  },
  {
    id: '2',
    name: 'Гуманітарний штаб "Миколаїв"',
    address: 'вул. Нікольська, 25, Миколаїв',
    lat: 46.9750,
    lng: 31.9946,
    category: 'Волонтерський штаб',
    services: 'Роздача продуктових наборів, забезпечення питною водою, евакуація населення.',
    phone: '+380 63 987 6543',
    email: 'help@mykolaiv.volunteer',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 12500000,
    region: 'Mykolaiv'
  },
  {
    id: '3',
    name: 'Херсонський Хаб "Я - Херсон"',
    address: 'пл. Свободи, 1, Херсон',
    lat: 46.6354,
    lng: 32.6169,
    category: 'Громадська організація',
    services: 'Психологічна підтримка, юридичні консультації, відновлення документів, шелтер.',
    phone: '+380 50 555 0101',
    email: 'support@kherson.hub',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 8100000,
    region: 'Kherson'
  },
  {
    id: '4',
    name: 'Карітас Одеса УГКЦ',
    address: 'вул. Південна, 40, Одеса',
    lat: 46.4580,
    lng: 30.7100,
    category: 'Релігійна місія',
    services: 'Догляд вдома, робота з дітьми та молоддю, кризовий центр, гуманітарна допомога.',
    phone: '+380 48 777 8899',
    email: 'caritas@odessa.ugcc',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 18000000,
    region: 'Odesa'
  },
  {
    id: '5',
    name: 'Червоний Хрест Миколаївщини',
    address: 'пр. Центральний, 12, Миколаїв',
    lat: 46.9660,
    lng: 32.0000,
    category: 'Міжнародна організація',
    services: 'Навчання першій допомозі, видача ваучерів, підтримка літніх людей.',
    phone: '+380 512 34 56 78',
    email: 'mk@redcross.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 30000000,
    region: 'Mykolaiv'
  },
  {
    id: '6',
    name: 'Волонтерський центр "Корабельний"',
    address: 'Корабельний район, Херсон',
    lat: 46.6100,
    lng: 32.5800,
    category: 'Волонтерський пункт',
    services: 'Гаряче харчування, пункти обігріву, допомога з будматеріалами.',
    phone: '+380 66 222 3344',
    email: 'korabelny@volunteer.ks',
    status: 'Pending',
    driveFolderUrl: DRIVE_URL,
    budget: 950000,
    region: 'Kherson'
  },
  {
    id: '7',
    name: 'БФ "ПОСМІШКА ЮА" (Одеса)',
    address: 'м. Одеса, Одеська область',
    lat: 46.4825,
    lng: 30.7233,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Odesa'
  },
  {
    id: '8',
    name: 'БФ "ПОСМІШКА ЮА" (Миколаїв)',
    address: 'м. Миколаїв, Миколаївська область',
    lat: 46.9600,
    lng: 32.0100,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Mykolaiv'
  },
  {
    id: '9',
    name: 'БФ "ПОСМІШКА ЮА" (Херсон)',
    address: 'м. Херсон, Херсонська область',
    lat: 46.6400,
    lng: 32.6100,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Kherson'
  },
  // --- NEW IMPORTED DATA FOR MYKOLAIV REGION ---
  
  // Багатопрофільна допомога (Миколаїв)
  {
    id: 'mk_new_1',
    name: 'Денний центр соціально-психологічної допомоги',
    address: 'м. Миколаїв, вул. Потьомкінська, 95а',
    lat: 46.9710, 
    lng: 32.0050,
    category: 'Центр допомоги',
    services: 'Особам, які постраждали від домашнього насильства або насильства за ознакою статі.',
    phone: '+38 (098) 899 32 53',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'mk_new_2',
    name: 'Простір «Коло сильних» (Жіночий консорціум України)',
    address: 'м. Миколаїв, вул. Маріупольська, 69',
    lat: 46.9680,
    lng: 31.9920,
    category: 'Громадська організація',
    services: 'Послуги кейс-менеджменту, психосоціальна підтримка, правова допомога, грошова допомога. Простір для жінок і дівчат.',
    phone: '+38 (067) 944 04 02',
    email: 'kolosilnih7@gmail.com',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'mk_new_3',
    name: 'БФ «Право на захист»',
    address: 'м. Миколаїв, вул. Садова, 25а',
    lat: 46.9650,
    lng: 32.0010,
    category: 'Благодійний фонд',
    services: 'Консультаційна та юридична допомога постраждалим від війни. Грошова допомога.',
    phone: '+38 (099) 507 50 90',
    email: 'o.mieshkova612@org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'mk_new_4',
    name: 'ГО «Десяте квітня»',
    address: 'м. Миколаїв, вул. Соборна 12б, офіс 205',
    lat: 46.9730,
    lng: 31.9930,
    category: 'Громадська організація',
    services: 'Кейс-менеджмент, правова допомога, психосоціальна підтримка, доступ до соцвиплат.',
    phone: '0800 33 28 58',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'mk_new_5',
    name: 'Intersos (Миколаїв)',
    address: 'м. Миколаїв',
    lat: 46.9620,
    lng: 31.9850,
    category: 'Міжнародна організація',
    services: 'Психологічна підтримка, медична допомога, соціальний супровід.',
    phone: '(093) 0798087',
    email: 'complaint.ukraine@intersos.org',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'mk_new_6',
    name: 'Центр психічного здоров`я MHPSS',
    address: 'м. Миколаїв, вул. Севастопольська 2',
    lat: 46.9690,
    lng: 31.9980,
    category: 'Медичний заклад',
    services: 'Кризова інтервенція, супровід постраждалих від насильства, EMDR терапія.',
    phone: '(099) 512 09 95',
    email: 'mhs.mykolaiv@gmail.com',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'mk_new_7',
    name: 'Zatyshno Space (Vostok SOS)',
    address: 'м. Миколаїв, вул. Марка Кропивницького 79а',
    lat: 46.9600,
    lng: 32.0200,
    category: 'Безпечний простір',
    services: 'Безпечний простір для жінок та дівчат. Юридична, психологічна, соціальна допомога.',
    phone: '0997900070',
    email: 'zatyshno.mykolaiv@east-sos.org',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'mk_new_8',
    name: 'Центр життєстійкості',
    address: 'м. Миколаїв, вул. 12 Поздовжня 50 а',
    lat: 46.9550,
    lng: 32.0300,
    category: 'Соціальний центр',
    services: 'Консультації психолога, соцпрацівника, групові заходи, програма "Батьківство без стресу".',
    phone: '(066) 635 38 80',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  
  // Медична допомога (Миколаїв)
  {
    id: 'med_1',
    name: 'Міська лікарня швидкої медичної допомоги',
    address: 'м. Миколаїв, вул. Корабелів, 14В',
    lat: 46.9630,
    lng: 31.9820,
    category: 'Медичний заклад',
    services: 'Екстрена медична допомога, стаціонарне лікування.',
    phone: '(0512) 47-47-47',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'med_2',
    name: 'Міська лікарня №3 (Дубки)',
    address: 'м. Миколаїв, вул. Космонавтів, 97',
    lat: 46.9350,
    lng: 32.0250,
    category: 'Медичний заклад',
    services: 'Багатопрофільна лікарня, приймальне відділення.',
    phone: '(0512) 44-49-69',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'med_3',
    name: 'Міська лікарня №5',
    address: 'м. Миколаїв, просп. Богоявленський, 336',
    lat: 46.8850,
    lng: 32.0150,
    category: 'Медичний заклад',
    services: 'Медична допомога мешканцям Корабельного району.',
    phone: '(0512) 64-10-01',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'med_4',
    name: 'Пологовий будинок №3',
    address: 'м. Миколаїв, вул. Київська, 3',
    lat: 46.9500,
    lng: 31.9700,
    category: 'Медичний заклад',
    services: 'Акушерська та гінекологічна допомога. Цілодобово.',
    phone: '(0512) 41-35-54',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'med_5',
    name: 'БФ «Здоров’я жінки і планування сім’ї»',
    address: 'м. Миколаїв, вул. Київська, 1',
    lat: 46.9510,
    lng: 31.9710,
    category: 'Благодійний фонд',
    services: 'Гінекологічний кабінет безбар’єрного доступу (на базі Обласної лікарні).',
    phone: '+38 (0512) 41 79 79',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },

  // Обласні актори (Вознесенськ, Первомайськ, Баштанка)
  {
    id: 'reg_1',
    name: 'Денний центр (Первомайськ)',
    address: 'м. Первомайськ, вул. Корабельна, 3',
    lat: 48.0438, 
    lng: 30.8500,
    category: 'Центр допомоги',
    services: 'Особам, які постраждали від домашнього насильства.',
    phone: '+38 (096) 064 33 58',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'reg_2',
    name: 'Мобільна бригада (Вознесенськ)',
    address: 'м. Вознесенськ',
    lat: 47.5606, 
    lng: 31.3330,
    category: 'Мобільна бригада',
    services: 'Соціально-психологічна допомога постраждалим від насильства.',
    phone: '+38 (096) 245 56 92',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'reg_3',
    name: 'Кабінет безбар’єрного доступу (Вознесенськ)',
    address: 'м. Вознесенськ, вул. 228-ї стрілецької дивізії, 26',
    lat: 47.5650, 
    lng: 31.3350,
    category: 'Медичний заклад',
    services: 'Гінекологічний кабінет на базі лікарні (за підтримки UNFPA).',
    phone: '+38 (05134) 3 26 47',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'reg_4',
    name: 'International Rescue Committee (Баштанка)',
    address: 'м. Баштанка',
    lat: 47.4068, 
    lng: 32.4414,
    category: 'Міжнародна організація',
    services: 'Послуга кейс-менеджменту для осіб, постраждалих від ГЗН.',
    phone: '+38 (063) 178 51 92',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'reg_5',
    name: 'Денний центр (Криве Озеро)',
    address: 'смт. Криве Озеро, вул. Шевченка, 57',
    lat: 47.9500, 
    lng: 30.3500,
    category: 'Центр допомоги',
    services: 'Особам, які постраждали від домашнього насильства. Кризова кімната.',
    phone: '+38 (096) 433 43 39',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: 'reg_6',
    name: 'Спеціалізована служба (Нова Одеса)',
    address: 'м. Нова Одеса, вул. Центральна, 210',
    lat: 47.3089, 
    lng: 31.7892,
    category: 'Соціальна служба',
    services: 'Первинне консультування постраждалих від насильства.',
    phone: '+38 (098) 257 27 87',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },

  // --- EXISTING REST ---
  {
    id: '10',
    name: 'ВТК «Феникс-Медикал»',
    address: 'м. Одеса',
    lat: 46.4750,
    lng: 30.7450,
    category: 'Компанія',
    services: 'Люди з інвалідністю (ТЗР)',
    phone: '+38 (067) 488-76-00',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '11',
    name: 'Благодійний фонд «Ассалам»',
    address: 'м. Одеса',
    lat: 46.4850,
    lng: 30.7150,
    category: 'Благодійний фонд',
    services: 'Переселенці; біженці',
    phone: '+38 (048) 780-13-04',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '12',
    name: 'Благодійний фонд «Подсолнух»',
    address: 'м. Одеса',
    lat: 46.4650,
    lng: 30.7350,
    category: 'Благодійний фонд',
    services: 'Діти з ОРА; діти-інваліди',
    phone: '+38 (048) 799-33-05',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '13',
    name: 'Благодійний фонд «Жива Надежда»',
    address: 'м. Одеса',
    lat: 46.4550,
    lng: 30.7250,
    category: 'Благодійний фонд',
    services: 'Діти/підлітки з малозабезпечених сімей',
    phone: '+38 (048) 787-47-98',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '14',
    name: 'БФ "Дорога до будинку" (Way Home)',
    address: 'м. Одеса',
    lat: 46.4715,
    lng: 30.7350,
    category: 'Благодійний фонд',
    services: 'Соціальна адаптація, робота з безпритульними, реабілітація',
    phone: '+38 (048) 777-20-76',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 5000000,
    region: 'Odesa'
  },
  {
    id: '15',
    name: 'БО "СІМ`Я" - "Територія Дітей"',
    address: 'м. Одеса',
    lat: 46.4600,
    lng: 30.7200,
    category: 'Благодійний фонд',
    services: 'Допомога сім\'ям, дітям, психологічна підтримка',
    phone: '+38 095-009-20-30',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '16',
    name: 'Притулок для жінок',
    address: 'м. Одеса',
    lat: 46.4900,
    lng: 30.7100,
    category: 'Комунальна установа',
    services: 'Притулок для жінок (при міському центрі соц. служб)',
    phone: '(048) 753-11-94',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '17',
    name: 'ТЦСО Приморського району',
    address: 'м. Одеса, Приморський р-н',
    lat: 46.4500,
    lng: 30.7500,
    category: 'Комунальна установа',
    services: 'Соціальне обслуговування пенсіонерів та вразливих груп',
    phone: '(048) 740-75-24',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '18',
    name: 'ТЦСО Пересипського району',
    address: 'м. Одеса, Пересипський р-н',
    lat: 46.5300,
    lng: 30.7600,
    category: 'Комунальна установа',
    services: 'Соціальне обслуговування, допомога вдома',
    phone: '(048) 763-03-60',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '19',
    name: 'Денний центр та Кризова кімната',
    address: 'Авангардівська громада',
    lat: 46.4800,
    lng: 30.6500,
    category: 'Комунальна установа',
    services: 'Допомога постраждалим від насильства, кризова кімната',
    phone: '+38 063-216-32-74',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '20',
    name: 'Мобільна бригада СПД',
    address: 'м. Білгород-Дністровський',
    lat: 46.1900,
    lng: 30.3500,
    category: 'Комунальна установа',
    services: 'Соціально-психологічна допомога',
    phone: '+38 063-216-29-48',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Odesa'
  },
  {
    id: '21',
    name: 'Благодійний фонд "Щедрик"',
    address: 'м. Миколаїв',
    lat: 46.9650,
    lng: 32.0150,
    category: 'Благодійний фонд',
    services: 'Гуманітарна допомога, підтримка дітей та родин',
    phone: '0800-33-78-45',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '22',
    name: 'Благодійна організація "Ласка"',
    address: 'м. Миколаїв',
    lat: 46.9550,
    lng: 32.0250,
    category: 'Благодійний фонд',
    services: 'Благодійна допомога',
    phone: '+38 067-137-05-05',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '23',
    name: 'БФ "СОС Дитячі Містечка"',
    address: 'м. Миколаїв',
    lat: 46.9700,
    lng: 31.9800,
    category: 'Благодійний фонд',
    services: 'Допомога сім\'ям, дітям-сиротам',
    phone: '+38 063-366-23-91',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '24',
    name: 'Обласний центр соціальних служб',
    address: 'м. Миколаїв',
    lat: 46.9800,
    lng: 31.9900,
    category: 'Комунальна установа',
    services: 'Координація соціальних послуг області',
    phone: '(0512) 37-64-92',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '25',
    name: 'КУ "Центр надання соціальних послуг"',
    address: 'м. Миколаїв',
    lat: 46.9400,
    lng: 32.0000,
    category: 'Комунальна установа',
    services: 'Надання соціальних послуг населенню',
    phone: '(03241) 52-2-58',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '26',
    name: 'ТЦСО Первомайської громади',
    address: 'м. Первомайськ',
    lat: 48.0400,
    lng: 30.8500,
    category: 'Комунальна установа',
    services: 'Соціальне обслуговування громади',
    phone: '(05161) 7-51-95',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '27',
    name: 'КЗ "Вознесенський ЦНСП"',
    address: 'м. Вознесенськ',
    lat: 47.5600,
    lng: 31.3300,
    category: 'Комунальна установа',
    services: 'Центр надання соціальних послуг',
    phone: '(05134) 3-26-50',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '28',
    name: 'ХОБФ "Об\'єднання"',
    address: 'м. Херсон',
    lat: 46.6450,
    lng: 32.6250,
    category: 'Благодійний фонд',
    services: 'Гуманітарна та соціальна допомога',
    phone: '+38 098-117-56-79',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '29',
    name: 'Благодійний фонд "Я – Херсон"',
    address: 'м. Херсон',
    lat: 46.6380,
    lng: 32.6120,
    category: 'Благодійний фонд',
    services: 'Всебічна допомога мешканцям Херсона',
    phone: '0800-33-94-74',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '30',
    name: 'Херсонський обласний фонд милосердя',
    address: 'м. Херсон',
    lat: 46.6300,
    lng: 32.6000,
    category: 'Благодійний фонд',
    services: 'Милосердя та здоров\'я',
    phone: '(0552) 26-50-39',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '31',
    name: 'ТЦСО Суворовського району',
    address: 'м. Херсон, Суворовський р-н',
    lat: 46.6500,
    lng: 32.6300,
    category: 'Комунальна установа',
    services: 'Територіальний центр соціального обслуговування',
    phone: '(0552) 22-97-34',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  {
    id: '32',
    name: 'КЗ "Нововоронцовський ЦНСП"',
    address: 'смт Нововоронцовка',
    lat: 47.3300,
    lng: 33.9100,
    category: 'Комунальна установа',
    services: 'Соціальні послуги для населення',
    phone: '(05134) 3-26-50',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Kherson'
  },
  // --- Нові регіони (Дніпро, Запоріжжя) ---
  {
    id: '33',
    name: 'БФ "ПОСМІШКА ЮА" (Дніпро)',
    address: 'м. Дніпро, Дніпропетровська область',
    lat: 48.4647,
    lng: 35.0462,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Dnipro'
  },
  {
    id: '34',
    name: 'БФ "ПОСМІШКА ЮА" (Запоріжжя)',
    address: 'м. Запоріжжя, Запорізька область',
    lat: 47.8388,
    lng: 35.1396,
    category: 'Благодійний фонд',
    services: 'Всі види допомоги (гуманітарна, психологічна, соціальна)',
    phone: '+380 50 460 2240',
    email: 'contact@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 100000000,
    region: 'Zaporizhzhia'
  },
  {
    id: '35',
    name: 'Шелтер переселенців (Дніпро)',
    address: 'м. Дніпро',
    lat: 48.4700,
    lng: 35.0500,
    category: 'Притулок',
    services: 'Тимчасове проживання для ВПО',
    phone: '+380 50 111 2233',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 500000,
    region: 'Dnipro'
  },
  // Миколаївські департаменти
  {
    id: '36',
    name: 'Департамент праці та соціального захисту (Миколаїв)',
    address: 'м. Миколаїв',
    lat: 46.9700,
    lng: 31.9900,
    category: 'Комунальна установа',
    services: 'Забезпечення соціальних гарантій учасників бойових дій, осіб з інвалідністю, ветеранів',
    phone: '',
    email: '',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '37',
    name: 'Управління соц. виплат (Інгульський р-н)',
    address: 'вул. Миколаївська, 26/1, Миколаїв',
    lat: 46.9450,
    lng: 32.0300,
    category: 'Комунальна установа',
    services: 'Соціальні виплати та компенсації',
    phone: '(0512) 58-61-69',
    email: 'utszn_lenin@ukr.net',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '38',
    name: 'Управління соц. виплат (Центральний р-н)',
    address: 'вул. Захисників Миколаєва (Декабристів), 25, Миколаїв',
    lat: 46.9720,
    lng: 31.9880,
    category: 'Комунальна установа',
    services: 'Соціальні виплати та компенсації',
    phone: '(0512) 47-79-05',
    email: 'utszn_centr@ukr.net',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '39',
    name: 'Управління соц. виплат (Заводський р-н)',
    address: 'вул. Морехідна, 9/2, Миколаїв',
    lat: 46.9630,
    lng: 31.9600,
    category: 'Комунальна установа',
    services: 'Соціальні виплати та компенсації',
    phone: '(0512) 40-91-28',
    email: 'utszn_zavodsk@ukr.net',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  },
  {
    id: '40',
    name: 'Управління соц. виплат (Корабельний р-н)',
    address: 'вул. Дмитра Пєтухова, 1/1, Миколаїв',
    lat: 46.8800,
    lng: 32.0200,
    category: 'Комунальна установа',
    services: 'Соціальні виплати та компенсації',
    phone: '(0512) 60-09-05',
    email: 'utszn_korab@ukr.net',
    status: 'Active',
    driveFolderUrl: DRIVE_URL,
    budget: 0,
    region: 'Mykolaiv'
  }
];
