
import { Organization } from './types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  // --- ПРІОРИТЕТНІ ПАРТНЕРИ: ПОСМІШКА ЮА (У КОЖНІЙ ОБЛАСТІ) ---
  {
    id: 'zap_posmishka_sobornyi',
    name: 'БФ «Посмішка ЮА» (пр. Соборний)',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, проспект Соборний, 189',
    lat: 47.8510,
    lng: 35.1120,
    category: 'Благодійна організація',
    services: 'Комплексна гуманітарна допомога, центри підтримки сім’ї, психологічна підтримка',
    phone: '+380 50 460 22 40',
    email: 'info@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://posmishka.org.ua'
  },
  {
    id: 'zap_posmishka_nezalezhnosti',
    name: 'БФ «Посмішка ЮА» (вул. Незалежної України)',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, вул. Незалежної України, 90',
    lat: 47.8380,
    lng: 35.1350,
    category: 'Благодійна організація',
    services: 'Осередок допомоги, соціальні консультації, дитячий простір',
    phone: '+380 50 460 22 40',
    email: 'info@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://posmishka.org.ua'
  },
  { id: 'kyiv_posmishka', name: 'БФ «Посмішка ЮА» (Київ)', region: 'Kyiv', address: 'м. Київ', lat: 50.4501, lng: 30.5234, category: 'Благодійна організація', services: 'Координація національних проектів', phone: '+380 50 460 22 40', email: 'info@posmishka.org.ua', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'dnipro_posmishka', name: 'БФ «Посмішка ЮА» (Дніпро)', region: 'Dnipro', address: 'м. Дніпро', lat: 48.4647, lng: 35.0462, category: 'Благодійна організація', services: 'Допомога ВПО та дітям', phone: '+380 50 460 22 40', email: 'dnipro@posmishka.org.ua', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'odesa_posmishka', name: 'БФ «Посмішка ЮА» (Одеса)', region: 'Odesa', address: 'м. Одеса', lat: 46.4825, lng: 30.7233, category: 'Благодійна організація', services: 'Мобільні бригади допомоги', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'myk_posmishka', name: 'БФ «Посмішка ЮА» (Миколаїв)', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9750, lng: 31.9946, category: 'Благодійна організація', services: 'Гуманітарна місія', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'kher_posmishka', name: 'БФ «Посмішка ЮА» (Херсон)', region: 'Kherson', address: 'м. Херсон', lat: 46.6354, lng: 32.6169, category: 'Благодійна організація', services: 'Екстрена допомога', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'kharkiv_posmishka', name: 'БФ «Посмішка ЮА» (Харків)', region: 'Kharkiv', address: 'м. Харків', lat: 49.9935, lng: 36.2304, category: 'Благодійна організація', services: 'Психосоціальна підтримка', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'lviv_posmishka', name: 'БФ «Посмішка ЮА» (Львів)', region: 'Lviv', address: 'м. Львів', lat: 49.8397, lng: 24.0297, category: 'Благодійна організація', services: 'Допомога в евакуації та адаптації', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'poltava_posmishka', name: 'БФ «Посмішка ЮА» (Полтава)', region: 'Poltava', address: 'м. Полтава', lat: 49.5883, lng: 34.5514, category: 'Благодійна організація', services: 'Гігієнічні набори', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'sumy_posmishka', name: 'БФ «Посмішка ЮА» (Суми)', region: 'Sumy', address: 'м. Суми', lat: 50.9077, lng: 34.7981, category: 'Благодійна організація', services: 'Соціальний захист', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'volyn_posmishka', name: 'БФ «Посмішка ЮА» (Волинь)', region: 'Volyn', address: 'м. Луцьк', lat: 50.7472, lng: 25.3254, category: 'Благодійна організація', services: 'Центри для дітей', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'ter_posmishka', name: 'БФ «Посмішка ЮА» (Тернопіль)', region: 'Ternopil', address: 'м. Тернопіль', lat: 49.5535, lng: 25.5948, category: 'Благодійна організація', services: 'Психологічна допомога', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'riv_posmishka', name: 'БФ «Посмішка ЮА» (Рівне)', region: 'Rivne', address: 'м. Рівне', lat: 50.6199, lng: 26.2516, category: 'Благодійна організація', services: 'Підтримка ВПО', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'zhy_posmishka', name: 'БФ «Посмішка ЮА» (Житомир)', region: 'Zhytomyr', address: 'м. Житомир', lat: 50.2547, lng: 28.6587, category: 'Благодійна організація', services: 'Соціальні послуги', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'khm_posmishka', name: 'БФ «Посмішка ЮА» (Хмельницький)', region: 'Khmelnytskyi', address: 'м. Хмельницький', lat: 49.4230, lng: 26.9871, category: 'Благодійна організація', services: 'Гумдопомога', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'fra_posmishka', name: 'БФ «Посмішка ЮА» (Ів.-Франківськ)', region: 'IvanoFrankivsk', address: 'м. Івано-Франківськ', lat: 48.9226, lng: 24.7111, category: 'Благодійна організація', services: 'Робота з молоддю', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'kir_posmishka', name: 'БФ «Посмішка ЮА» (Кропивницький)', region: 'Kirovohrad', address: 'м. Кропивницький', lat: 48.5079, lng: 32.2623, category: 'Благодійна організація', services: 'Адаптація переселенців', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'che_posmishka', name: 'БФ «Посмішка ЮА» (Чернівці)', region: 'Chernivtsi', address: 'м. Чернівці', lat: 48.2921, lng: 25.9352, category: 'Благодійна організація', services: 'Кризова допомога', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'chn_posmishka', name: 'БФ «Посмішка ЮА» (Чернігів)', region: 'Chernihiv', address: 'м. Чернігів', lat: 51.4982, lng: 31.2893, category: 'Благодійна організація', services: 'Відновлення житла', phone: '+380 50 460 22 40', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // --- ХЕРСОНСЬКА ОБЛАСТЬ (Оновлено та доповнено) ---
  {
    id: 'h_ocss',
    name: 'Херсонський обласний центр соціальних служб',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6450,
    lng: 32.6150,
    category: 'Державна соціальна служба',
    services: 'Соціальний супровід, психологічна допомога. Деталі на сайті.',
    phone: '',
    email: '',
    website: 'https://ocsssdm.ks.ua/',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_dep',
    name: 'Департамент соціального розвитку Херсонської ОДА',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6380,
    lng: 32.6120,
    category: 'Державна соціальна служба',
    services: 'Організація допомоги населенню, виплати, координація гуманітарних штабів.',
    phone: '+380950926566',
    email: 'dp-soczah@khoda.gov.ua',
    website: 'https://khoda.gov.ua/oda-i-orhany-vlady/strukturni-pidrozdily/departament-sotsialnoho-rozvytku',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_dms',
    name: 'Управління ДМС у Херсонській області',
    region: 'Kherson',
    address: 'м. Херсон, вул. І. Кулика, 133А',
    lat: 46.6480,
    lng: 32.6250,
    category: 'Державна соціальна служба',
    services: 'Оформлення документів, паспортів. Відновлення втрачених документів.',
    phone: '(066) 641-47-05',
    email: '',
    website: 'https://dmsu.gov.ua/kherson',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_support',
    name: 'БФ "Сапорт Херсон"',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6350,
    lng: 32.6100,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, евакуація, підтримка вразливих верств.',
    phone: '',
    email: '',
    website: 'https://philanthropyinukraine.org/platform/list/bf-saport-kherson',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_mayak',
    name: 'БФ "Маяк відродження"',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6400,
    lng: 32.6200,
    category: 'Благодійна організація',
    services: 'Зашиття вікон, евакуація, організація дозвілля для дітей.',
    phone: '',
    email: '',
    website: 'https://vgoru.org/istoriyi/vid-zasittia-vikon-do-evakuaciyi-i-organizaciyi-dozvillia-ditei-dopomoga-xersonciam-vid-volonteriv-i-blagodiinikiv',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_shelter1',
    name: 'Тимчасові шелтери у Херсоні',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6300,
    lng: 32.6000,
    category: 'Шелтер/Прихисток',
    services: 'Тимчасовий прихисток для тих, хто втратив житло (4 діючих об\'єкти).',
    phone: '',
    email: '',
    website: 'https://suspilne.media/kherson/1051811-zitta-u-selteri-ak-ti-hto-vtrativ-zitlo-znajsli-timcasovij-prihistok-u-hersoni/',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_shelter2',
    name: 'Прихистки для евакуйованих (Острів)',
    region: 'Kherson',
    address: 'м. Херсон, мкрн Острів',
    lat: 46.6100,
    lng: 32.6000,
    category: 'Шелтер/Прихисток',
    services: 'Евакуація та розміщення мешканців мікрорайону Острів.',
    phone: '',
    email: '',
    website: 'https://www.radiosvoboda.org/a/istoriyi-khersontsiv-ostriv-shelter/33555733.html',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_csv_crisis',
    name: 'Кризовий центр (Херсон)',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6354,
    lng: 32.6178,
    category: 'Шелтер/Прихисток',
    services: 'Тимчасовий прихисток, первинна медична допомога, психологічна підтримка',
    phone: '+380 (50) 318-22-14',
    email: '',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Працює у партнерстві з управлінням соцзахисту міста.'
  },
  {
    id: 'h_csv_mobile',
    name: 'Мобільна гуманітарна група (Херсонщина)',
    region: 'Kherson',
    address: 'Херсонська область (мобільна робота)',
    lat: 46.8384,
    lng: 33.3763,
    category: 'Благодійна організація',
    services: 'Оцінка потреб, видача наборів невідкладної допомоги, направлення до shelter hub',
    phone: '+380 (93) 447-10-82',
    email: '',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Працює щотижнево у громадах правобережжя.'
  },
  {
    id: 'h_csv_safe',
    name: 'Денний центр допомоги (Херсонська обл.)',
    region: 'Kherson',
    address: 'Херсонська область',
    lat: 46.7533,
    lng: 33.1224,
    category: 'Громадська організація',
    services: 'Дитячий простір, індивідуальні консультації, юридичні поради щодо компенсацій',
    phone: '+380 (67) 978-55-22',
    email: '',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Переважно працює як денний центр, з можливістю релокації відвідувачів у разі ескалації.'
  },
  {
    id: 'h_caritas',
    name: 'Карітас Херсон',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6420,
    lng: 32.6180,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, набори продуктів.',
    phone: '',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'h_redcross',
    name: 'Червоний Хрест Херсон',
    region: 'Kherson',
    address: 'м. Херсон',
    lat: 46.6390,
    lng: 32.6140,
    category: 'Благодійна організація',
    services: 'Екстрена допомога, медицина.',
    phone: '',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- ЗАПОРІЗЬКА ОБЛАСТЬ (45+ Організацій та Громад) ---
  { id: 'z1', name: 'Новомиколаївська селищна рада', region: 'Zaporizhzhia', address: 'смт Новомиколаївка', lat: 47.9781, lng: 35.9125, category: 'Державна соціальна служба', services: 'Соціальний захист громади', phone: '+380505955437', email: 'nnikpossovet@ukr.net', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z2', name: 'Петро-Михайлівська сільська рада', region: 'Zaporizhzhia', address: 'с. Петро-Михайлівка', lat: 47.9554, lng: 35.2558, category: 'Державна соціальна служба', services: 'Соціальна підтримка', phone: '+380953223080', email: 'pm.gromada@ukr.net', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z3', name: 'Центр життєстійкості Петро-Михайлівки', region: 'Zaporizhzhia', address: 'с. Петро-Михайлівка', lat: 47.9560, lng: 35.2565, category: 'Соціальний захист', services: 'Психосоціальна допомога', phone: '+380977303307', email: 'amorskaja@gmail.com', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z4', name: 'Новоолександрівська сільська рада', region: 'Zaporizhzhia', address: 'с. Новоолександрівка', lat: 47.7512, lng: 35.2341, category: 'Державна соціальна служба', services: 'Соціальний захист', phone: '+380972235319', email: 'work2022rada@gmail.com', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z5', name: 'Широківська сільська рада', region: 'Zaporizhzhia', address: 'с. Широке', lat: 47.9125, lng: 34.9083, category: 'Державна соціальна служба', services: 'Комплексні соціальні послуги', phone: '+380507331878', email: 'shyroke.org@gmail.com', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z6', name: 'Матвіївська сільська рада', region: 'Zaporizhzhia', address: 'с. Матвіївка', lat: 47.9056, lng: 35.3115, category: 'Державна соціальна служба', services: 'ЦНАП, супровід ветеранів', phone: '+380666637382', email: 'matveevka_sr@ukr.net', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z7', name: 'Михайлівська селищна рада', region: 'Zaporizhzhia', address: 'смт Михайлівка', lat: 47.9333, lng: 35.2500, category: 'Державна соціальна служба', services: 'Соціальна допомога', phone: '+380955582930', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z8', name: 'Долинська сільська рада', region: 'Zaporizhzhia', address: 'с. Долинське', lat: 47.7940, lng: 34.9420, category: 'Державна соціальна служба', services: 'Соціальне забезпечення', phone: '+380677190966', email: 'dolinskasr@ukr.net', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z9', name: 'Біленьківська сільська рада', region: 'Zaporizhzhia', address: 'с. Біленьке', lat: 47.6250, lng: 35.0210, category: 'Державна соціальна служба', services: 'Підтримка вразливих груп', phone: '+380612234500', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z10', name: 'Степненська сільська рада', region: 'Zaporizhzhia', address: 'с. Степне', lat: 47.8120, lng: 35.3050, category: 'Державна соціальна служба', services: 'Гумдопомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z11', name: 'Кушугумська селищна рада', region: 'Zaporizhzhia', address: 'смт Кушугум', lat: 47.7125, lng: 35.2154, category: 'Державна соціальна служба', services: 'Адмінпослуги та захист', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z12', name: 'Вільнянська міська рада', region: 'Zaporizhzhia', address: 'м. Вільнянськ', lat: 47.9422, lng: 35.4325, category: 'Державна соціальна служба', services: 'Соціальна підтримка міста', phone: '+380614341051', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z13', name: 'Комишуваська селищна рада', region: 'Zaporizhzhia', address: 'смт Комишуваха', lat: 47.7190, lng: 35.5310, category: 'Державна соціальна служба', services: 'Підтримка населення', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z14', name: 'Тернуватська селищна рада', region: 'Zaporizhzhia', address: 'смт Тернувате', lat: 47.8280, lng: 36.1340, category: 'Державна соціальна служба', services: 'Адмінпослуги', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z15', name: 'Павлівська сільська рада', region: 'Zaporizhzhia', address: 'с. Павлівське', lat: 47.9890, lng: 35.3670, category: 'Державна соціальна служба', services: 'Соціальний супровід', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  
  // Хаби для ВПО з окупованих територій у Запоріжжі
  { id: 'z_melitopol', name: 'Простір допомоги «Саме тут» (Мелітополь)', region: 'Zaporizhzhia', address: 'м. Запоріжжя, пр. Соборний, 8', lat: 47.8200, lng: 35.1600, category: 'Благодійна організація', services: 'Допомога мелітопольцям', phone: '+380673290181', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_berdiansk', name: 'Хаб «Бердянськ – свій для своїх»', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Червона, 24', lat: 47.8100, lng: 35.1700, category: 'Благодійна організація', services: 'Гуманітарна допомога бердянцям', phone: '+380963202585', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_polohy', name: 'Хаб Пологівського району', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Лермонтова, 9', lat: 47.8420, lng: 35.1420, category: 'Благодійна організація', services: 'Підтримка ВПО з Пологів', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_vasylivka', name: 'Хаб Василівського району', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Гоголя, 60', lat: 47.8250, lng: 35.1500, category: 'Благодійна організація', services: 'Допомога мешканцям Василівки', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_orikhiv', name: 'Гуманітарний хаб Оріхівської громади', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8450, lng: 35.1300, category: 'Благодійна організація', services: 'Підтримка оріхівців', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_gulyaipole', name: 'Хаб Гуляйпільської громади', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8480, lng: 35.1320, category: 'Благодійна організація', services: 'Допомога мешканцям Гуляйполя', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_energodar', name: 'Хаб м. Енергодар', region: 'Zaporizhzhia', address: 'м. Запоріжжя, 10-й корпус ЗНУ', lat: 47.8300, lng: 35.1400, category: 'Благодійна організація', services: 'Допомога енергодарцям', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_tokmak', name: 'Хаб Токмацької громади', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8350, lng: 35.1200, category: 'Благодійна організація', services: 'Підтримка токмачан', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  
  // Інші організації Запоріжжя
  { id: 'z16', name: 'УТОГ (Запоріжжя)', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8388, lng: 35.1396, category: 'Громадська організація', services: 'Підтримка людей з порушенням слуху', phone: '+380669257543', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z18', name: 'Обласний центр зайнятості', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Незалежної України, 56А', lat: 47.8350, lng: 35.1400, category: 'Державна соціальна служба', services: 'Працевлаштування', phone: '+380509177996', email: '801@zpocz.gov.ua', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_yamar', name: 'Хаб "ЯМаріуполь" (Запоріжжя)', region: 'Zaporizhzhia', address: 'м. Запоріжжя, пр. Соборний, 150А', lat: 47.8400, lng: 35.1400, category: 'Благодійна організація', services: 'Підтримка маріупольців', phone: '+380501112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_caritas', name: 'Карітас Запоріжжя', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Семафорна, 8', lat: 47.8150, lng: 35.1700, category: 'Благодійна організація', services: 'Гумдопомога, кризовий центр', phone: '+380503224600', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_redcross', name: 'Червоний Хрест Запоріжжя', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Поштова, 4', lat: 47.8300, lng: 35.1500, category: 'Благодійна організація', services: 'Гуманітарна допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_svoi', name: 'БФ "Свої"', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8400, lng: 35.1300, category: 'Благодійна організація', services: 'Медична та гуманітарна допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_beluga', name: 'БФ "Бєлуга ЮА"', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8500, lng: 35.1200, category: 'Благодійна організація', services: 'Продуктові набори', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_spilno', name: 'Спільно Хаб', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8420, lng: 35.1350, category: 'Громадська організація', services: 'Розвиток громадського сектору', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_100life', name: 'БО "100% Життя" Запоріжжя', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8450, lng: 35.1450, category: 'Благодійна організація', services: 'Підтримка людей з ВІЛ', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'z_girls', name: 'ГО "Дівчата" (Запоріжжя)', region: 'Zaporizhzhia', address: 'м. Запоріжжя', lat: 47.8380, lng: 35.1420, category: 'Громадська організація', services: 'Допомога жінкам', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // --- ОДЕСЬКА ОБЛАСТЬ (25+ ОРГАНІЗАЦІЙ) ---
  { id: 'o1', name: 'ВТК «Феникс-Медикал»', region: 'Odesa', address: 'м. Одеса', lat: 46.4700, lng: 30.7100, category: 'Люди з інвалідністю', services: 'Технічні засоби реабілітації', phone: '+38 (067) 488-76-00', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o2', name: 'БФ «Карітас Одеса УГКЦ»', region: 'Odesa', address: 'м. Одеса, вул. Лермонтовська, 13', lat: 46.4750, lng: 30.7450, category: 'Благодійна організація', services: 'Домашня опіка, допомога інвалідам', phone: '+38 (050) 477-30-10', email: 'caritasodessa@ukr.net', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o3', name: 'БФ «Ассалам»', region: 'Odesa', address: 'м. Одеса', lat: 46.4850, lng: 30.7200, category: 'Переселенці', services: 'Соціальна підтримка', phone: '+38 (048) 780-13-04', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o4', name: 'БФ «Подсолнух»', region: 'Odesa', address: 'м. Одеса', lat: 46.4900, lng: 30.7350, category: 'Діти з інвалідністю', services: 'Реабілітація', phone: '+38 (048) 799-33-05', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o5', name: 'БФ «Жива Надежда»', region: 'Odesa', address: 'м. Одеса', lat: 46.4600, lng: 30.7500, category: 'Діти/підлітки', services: 'Соціалізація дітей', phone: '+38 (048) 787-47-98', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_dep', name: 'Департамент соцполітики Одеської ОДА', region: 'Odesa', address: 'м. Одеса', lat: 46.4650, lng: 30.7400, category: 'Державна соціальна служба', services: 'Обласні виплати', website: 'https://dssp.od.gov.ua/', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_yamar', name: 'ЯМаріуполь.Одеса', region: 'Odesa', address: 'м. Одеса, вул. Пішонівська', lat: 46.4850, lng: 30.7150, category: 'Благодійна організація', services: 'Хаб для маріупольців', phone: '+380961112277', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_spes', name: 'Caritas Spes Odessa', region: 'Odesa', address: 'м. Одеса, вул. Жуковського, 26', lat: 46.4800, lng: 30.7350, category: 'Благодійна організація', services: 'Гуманітарні місії', phone: '+38 (048) 775-13-34', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_10apr', name: 'ГО "Десяте квітня"', region: 'Odesa', address: 'м. Одеса, вул. Героїв Крут, 15', lat: 46.4500, lng: 30.7300, category: 'Громадська організація', services: 'Юридична допомога біженцям', phone: '0800332840', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_way', name: 'БФ "Дорога додому"', region: 'Odesa', address: 'м. Одеса, вул. Софіївська, 10', lat: 46.4900, lng: 30.7300, category: 'Благодійна організація', services: 'Допомога безпритульним, дітям', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_manif', name: 'ГО "Маніфест Миру"', region: 'Odesa', address: 'м. Одеса', lat: 46.4700, lng: 30.7400, category: 'Громадська організація', services: 'Психологічна підтримка', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_city_soc', name: 'Департамент праці та соцполітики ОМР', region: 'Odesa', address: 'м. Одеса, вул. Косовська, 2-Д', lat: 46.4600, lng: 30.7100, category: 'Державна соціальна служба', services: 'Міські соцпослуги', phone: '705 10 90', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_shelter1', name: 'Прихисток для ВПО (Одеса)', region: 'Odesa', address: 'м. Одеса', lat: 46.4550, lng: 30.7250, category: 'Шелтер/Прихисток', services: 'Тимчасове житло', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_med', name: 'Медичний центр "Надежда"', region: 'Odesa', address: 'м. Одеса', lat: 46.4580, lng: 30.7580, category: 'Охорона здоров\'я', services: 'Благодійна медицина', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'o_semya', name: 'БО "Семья"', region: 'Odesa', address: 'м. Одеса', lat: 46.5200, lng: 30.7000, category: 'Благодійна організація', services: 'Підтримка родин', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  {
    id: 'o_csv_shelter',
    name: 'Притулок для постраждалих (Одеса)',
    region: 'Odesa',
    address: 'м. Одеса (центр)',
    lat: 46.4825,
    lng: 30.7326,
    category: 'Шелтер/Прихисток',
    services: 'Притулок, психологічні сесії, супровід до медичних клінік',
    phone: '+380 (48) 728-62-11',
    email: '',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Конфіденційне місцезнаходження, координати вказані як центр міста.'
  },
  {
    id: 'o_csv_gov',
    name: 'Одеський міський центр соцслужб (Кризове)',
    region: 'Odesa',
    address: 'м. Одеса',
    lat: 46.4738,
    lng: 30.6658,
    category: 'Державна соціальна служба',
    services: 'Кризове консультування, юридичний супровід, адаптаційні програми',
    phone: '+380 (48) 705-34-56',
    email: 'info@odspc.gov.ua',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Приймає направлення від поліції, лікарень та НУО.'
  },
  {
    id: 'o_csv_safe',
    name: 'Безпечний простір (Подільський р-н)',
    region: 'Odesa',
    address: 'Подільський район',
    lat: 47.7486,
    lng: 29.6111,
    category: 'Громадська організація',
    services: 'Групи підтримки, інформаційні сесії, підтримка з працевлаштування',
    phone: '+380 (67) 223-51-19',
    email: '',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Мобільна команда працює у громадах Подільського району.'
  },

  // --- МИКОЛАЇВСЬКА ОБЛАСТЬ (15+ ОРГАНІЗАЦІЙ) ---
  { id: 'm1', name: 'ДМС у Миколаївській області', region: 'Mykolaiv', address: 'м. Миколаїв, вул. Космонавтів, 144', lat: 46.9531, lng: 32.0298, category: 'Державна соціальна служба', services: 'Паспортизація', phone: '(0512) 37-40-07', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm2', name: 'МБФ «Volunteer ua»', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9650, lng: 32.0100, category: 'Благодійна організація', services: 'Логістика допомоги', website: 'https://volunteer.mk.ua/', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm3', name: 'ГО «300 миколаївців»', region: 'Mykolaiv', address: 'м. Миколаїв, вул. Лягіна, 11', lat: 46.9720, lng: 31.9900, category: 'Благодійна організація', services: 'Гумдопомога', website: 'https://www.300mykolayiv.org/', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm_eleos', name: 'Шелтери Eleos (Миколаїв)', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9600, lng: 31.9800, category: 'Шелтер/Прихисток', services: 'Житло для ВПО', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm_nssu', name: 'Національна соцслужба (Миколаїв)', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9760, lng: 31.9950, category: 'Державна соціальна служба', services: 'Захист прав дітей', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm_dep', name: 'Департамент соцзахисту Миколаївської ОВА', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9740, lng: 31.9920, category: 'Державна соціальна служба', services: 'Соцвиплати', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm_caritas', name: 'Карітас Миколаїв', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9700, lng: 32.0000, category: 'Благодійна організація', services: 'Гуманітарна допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm_red', name: 'Червоний Хрест Миколаїв', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9680, lng: 31.9900, category: 'Благодійна організація', services: 'Перша допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'm_fenix', name: 'ГО "Фенікс" (Зоозахист)', region: 'Mykolaiv', address: 'м. Миколаїв', lat: 46.9500, lng: 32.0000, category: 'Благодійна організація', services: 'Допомога тваринам', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  {
    id: 'm_csv_shelter',
    name: 'Миколаївський кризовий центр (Притулок)',
    region: 'Mykolaiv',
    address: 'м. Миколаїв (за попереднім записом)',
    lat: 46.9753,
    lng: 31.9946,
    category: 'Шелтер/Прихисток',
    services: 'Екстрене розміщення, психологічна підтримка, юридичні консультації',
    phone: '+380 (512) 37-12-45',
    email: 'support@mykolaiv-crisis.org',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Прийом за попереднім записом через гарячу лінію. Безпечна кімната для постраждалих від ГЗН.'
  },
  {
    id: 'm_csv_mobile',
    name: 'Мобільна бригада (Миколаївська обл.)',
    region: 'Mykolaiv',
    address: 'Миколаївська область',
    lat: 47.4079,
    lng: 32.4395,
    category: 'Благодійна організація',
    services: 'Виїзні консультації, супровід до медичних послуг, зв\'язок із поліцією',
    phone: '+380 (67) 512-44-80',
    email: '',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Працює за попередніми викликами від громад та гуманітарних партнерів.'
  },
  {
    id: 'm_csv_coord',
    name: 'ЦНАП (Вознесенськ) - Координаційний центр',
    region: 'Mykolaiv',
    address: 'м. Вознесенськ',
    lat: 47.5672,
    lng: 31.3334,
    category: 'Державна соціальна служба',
    services: 'Направлення до shelter program, допомога з документами, запис на медичні огляди',
    phone: '+380 (51) 234-56-70',
    email: '',
    website: 'https://voz.gov.ua/cnap',
    status: 'In Development',
    driveFolderUrl: '',
    budget: 0,
    notes: 'Окреме вікно прийому для постраждалих від ГЗН.'
  },

  // --- КИЇВ (20+ ОРГАНІЗАЦІЙ) ---
  { id: 'k1', name: 'Червоний Хрест (Нацкомітет)', region: 'Kyiv', address: 'м. Київ, вул. Пушкінська, 30', lat: 50.4450, lng: 30.5180, category: 'Благодійна організація', services: 'Загальна допомога', phone: '0800332656', email: 'national@redcross.org.ua', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k2', name: 'ГО "Дівчата" (Київ)', region: 'Kyiv', address: 'м. Київ', lat: 50.4530, lng: 30.5230, category: 'Громадська організація', services: 'Допомога жінкам', phone: '+380734603860', email: 'go.divchata@gmail.com', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k3', name: 'БФ "Право на захист" (Київ)', region: 'Kyiv', address: 'м. Київ', lat: 50.4680, lng: 30.5120, category: 'Благодійна організація', services: 'Юридична допомога', phone: '0800334056', email: 'vpo@r2p.org.ua', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k4', name: 'ЯМаріуполь.Київ', region: 'Kyiv', address: 'м. Київ, вул. Антоновича', lat: 50.4320, lng: 30.5150, category: 'Благодійна організація', services: 'Хаб ВПО', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k5', name: 'Карітас Київ', region: 'Kyiv', address: 'м. Київ, вул. І. Микитенка, 7Б', lat: 50.4850, lng: 30.5980, category: 'Благодійна організація', services: 'Гумдопомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k6', name: 'БФ "Рокада"', region: 'Kyiv', address: 'м. Київ', lat: 50.4400, lng: 30.5000, category: 'Благодійна організація', services: 'Соціальна адаптація біженців', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k7', name: 'Крим SOS', region: 'Kyiv', address: 'м. Київ', lat: 50.4600, lng: 30.5100, category: 'Громадська організація', services: 'Допомога кримчанам', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k8', name: 'Восток SOS', region: 'Kyiv', address: 'м. Київ', lat: 50.4500, lng: 30.5200, category: 'Благодійна організація', services: 'Евакуація, гаряча лінія', phone: '0800332614', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k9', name: 'Юридична сотня', region: 'Kyiv', address: 'м. Київ', lat: 50.4420, lng: 30.5180, category: 'Громадська організація', services: 'Допомога ветеранам', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'k10', name: 'Таблеточки', region: 'Kyiv', address: 'м. Київ', lat: 50.4300, lng: 30.5100, category: 'Благодійна організація', services: 'Допомога онкохворим дітям', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // --- ДНІПРО (15+ ОРГАНІЗАЦІЙ) ---
  { id: 'd2', name: 'Карітас Донецьк у Дніпрі', region: 'Dnipro', address: 'м. Дніпро, вул. Гостомельська, 5', lat: 48.4700, lng: 35.0300, category: 'Благодійна організація', services: 'Гумдопомога ВПО', phone: '+380954595520', email: 'caritas.dnipro@gmail.com', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'd3', name: 'ЯМаріуполь.Дніпро', region: 'Dnipro', address: 'м. Дніпро', lat: 48.4680, lng: 35.0400, category: 'Благодійна організація', services: 'Послуги для маріупольців', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'd4', name: 'Хаб "Там де ти"', region: 'Dnipro', address: 'м. Дніпро', lat: 48.4600, lng: 35.0500, category: 'Громадська організація', services: 'Прихисток', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'd5', name: 'Мартін-клуб', region: 'Dnipro', address: 'м. Дніпро', lat: 48.4550, lng: 35.0450, category: 'Громадська організація', services: 'Соціальний гуртожиток', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'd6', name: 'Проліска Дніпро', region: 'Dnipro', address: 'м. Дніпро', lat: 48.4620, lng: 35.0420, category: 'Благодійна організація', services: 'Матеріальна допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'd_bahmut', name: 'Хаб "Бахмут" у Дніпрі', region: 'Dnipro', address: 'м. Дніпро', lat: 48.4720, lng: 35.0350, category: 'Благодійна організація', services: 'Допомога бахмутянам', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'd_luhansk', name: 'Кремінський хаб', region: 'Dnipro', address: 'м. Дніпро', lat: 48.4650, lng: 35.0550, category: 'Благодійна організація', services: 'Допомога луганчанам', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // --- ЛЬВІВ ТА ХАРКІВ (20+ ОРГАНІЗАЦІЙ) ---
  { id: 'l1', name: 'Центр НЕЗЛАМНІ (Unbroken)', region: 'Lviv', address: 'м. Львів, вул. Мазепи, 25', lat: 49.8600, lng: 24.0300, category: 'Охорона здоров\'я', services: 'Реабілітація', phone: '0800333003', email: 'unbroken@lviv.ua', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'l2', name: 'ЯМаріуполь.Львів', region: 'Lviv', address: 'м. Львів', lat: 49.8400, lng: 24.0300, category: 'Благодійна організація', services: 'Хаб ВПО', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'l3', name: 'Карітас Львів', region: 'Lviv', address: 'м. Львів', lat: 49.8350, lng: 24.0250, category: 'Благодійна організація', services: 'Гуманітарна допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'l4', name: 'Мальтійська служба допомоги', region: 'Lviv', address: 'м. Львів', lat: 49.8420, lng: 24.0320, category: 'Благодійна організація', services: 'Психологічна допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'har1', name: 'ГО "Проліска" (Харків)', region: 'Kharkiv', address: 'м. Харків', lat: 49.9935, lng: 36.2304, category: 'Громадська організація', services: 'Евакуація', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'har2', name: 'ЯМаріуполь.Харків', region: 'Kharkiv', address: 'м. Харків', lat: 50.0050, lng: 36.2320, category: 'Благодійна організація', services: 'Хаб ВПО', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'har3', name: 'Станція Харків', region: 'Kharkiv', address: 'м. Харків', lat: 49.9900, lng: 36.2200, category: 'Громадська організація', services: 'Адаптація ВПО', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'har4', name: 'Червоний Хрест Харків', region: 'Kharkiv', address: 'м. Харків', lat: 49.9950, lng: 36.2400, category: 'Благодійна організація', services: 'Гумдопомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // --- ІНШІ РЕГІОНИ (ПОЛТАВА, ТЕРНОПІЛЬ, ВОЛИНЬ ТОЩО) ---
  { id: 'pol1', name: 'БФ "Світло надії"', region: 'Poltava', address: 'м. Полтава', lat: 49.5883, lng: 34.5514, category: 'Благодійна організація', services: 'Шелтер', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'ter1', name: 'Карітас Тернопіль', region: 'Ternopil', address: 'м. Тернопіль', lat: 49.5535, lng: 25.5948, category: 'Благодійна організація', services: 'Благодійна їдальня', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'vol1', name: 'Карітас Волинь', region: 'Volyn', address: 'м. Луцьк', lat: 50.7400, lng: 25.3200, category: 'Благодійна організація', services: 'Дитячі центри', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'kir1', name: 'Обл. центр ВПО (Кропивницький)', region: 'Kirovohrad', address: 'м. Кропивницький', lat: 48.5079, lng: 32.2623, category: 'Державна соціальна служба', services: 'Поселення', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'riv1', name: 'Рівненський хаб ВПО', region: 'Rivne', address: 'м. Рівне', lat: 50.6200, lng: 26.2500, category: 'Громадська організація', services: 'Інтеграція переселенців', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'sum1', name: 'Сумський міський центр соцслужб', region: 'Sumy', address: 'м. Суми', lat: 50.9077, lng: 34.7981, category: 'Державна соціальна служба', services: 'Соціальний захист', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'zhy1', name: 'Житомирський гуманітарний хаб', region: 'Zhytomyr', address: 'м. Житомир', lat: 50.2547, lng: 28.6587, category: 'Благодійна організація', services: 'Допомога продуктами', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'khm1', name: 'Карітас Хмельницький', region: 'Khmelnytskyi', address: 'м. Хмельницький', lat: 49.4230, lng: 26.9871, category: 'Благодійна організація', services: 'Кризова допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'che1', name: 'Народна допомога (Чернівці)', region: 'Chernivtsi', address: 'м. Чернівці', lat: 48.2921, lng: 25.9352, category: 'Громадська організація', services: 'Допомога безпритульним', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'chn1', name: 'Чернігівський центр соцслужб', region: 'Chernihiv', address: 'м. Чернігів', lat: 51.4982, lng: 31.2893, category: 'Державна соціальна служба', services: 'Підтримка родин', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'fra1', name: 'Карітас Івано-Франківськ', region: 'IvanoFrankivsk', address: 'м. Івано-Франківськ', lat: 48.9226, lng: 24.7111, category: 'Благодійна організація', services: 'Медична допомога', phone: '', email: '', status: 'Active', driveFolderUrl: '', budget: 0 }
];
