
import { Organization } from './types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  // --- ZAPORIZHZHIA REGION (Core Partner: Posmishka UA) ---
  {
    id: 'zap_posmishka',
    name: 'БФ «Посмішка ЮА» (Запоріжжя)',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, проспект Соборний, 151',
    lat: 47.8488,
    lng: 35.1396,
    category: 'Благодійна організація',
    services: 'Комплексна гуманітарна допомога, центри підтримки сім’ї, простір дружній до дитини, психологічна підтримка',
    phone: '+380 50 460 22 40',
    email: 'info@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://posmishka.org.ua',
    notes: 'Генеральний партнер проекту'
  },
  {
    id: 'zap_caritas',
    name: 'Карітас Запоріжжя',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, вул. Семафорна, 8',
    lat: 47.8200,
    lng: 35.1600,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, догляд вдома, робота з дітьми, кризовий центр',
    phone: '+380 50 322 46 00',
    email: 'caritas.zp@gmail.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zap_redcross',
    name: 'Червоний Хрест Запоріжжя',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, вул. Поштова, 4',
    lat: 47.8300,
    lng: 35.1400,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, евакуація',
    phone: '0612123456',
    email: 'redcross.zp@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zap_soc_dept',
    name: 'Департамент соцзахисту населення ЗОДА',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, вул. Олександрівська, 48',
    lat: 47.8250,
    lng: 35.1700,
    category: 'Державна соціальна служба',
    services: 'Державні виплати, допомога ВПО',
    phone: '(061) 764-41-45',
    email: 'soczah.zp@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zap_city_council',
    name: 'Запорізька міська рада',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, пр. Соборний, 206',
    lat: 47.8500,
    lng: 35.1100,
    category: 'Державна соціальна служба',
    services: 'Адміністративні послуги, соціальні програми міста',
    phone: '0800503508',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://zp.gov.ua/'
  },
  {
    id: 'zap_veteran_center',
    name: 'Центр допомоги ветеранам АТО',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, вул. Перемоги, 13',
    lat: 47.8150,
    lng: 35.1550,
    category: 'Соціальний захист',
    services: 'Психологічна підтримка, реабілітація, юридичні консультації для ветеранів',
    phone: '0671234567',
    email: 'veteran.zp@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zap_volunteer_hq',
    name: 'Запорізький волонтерський штаб',
    region: 'Zaporizhzhia',
    address: 'м. Запоріжжя, вул. Незалежної України, 55А',
    lat: 47.8220,
    lng: 35.1320,
    category: 'Волонтерська організація',
    services: 'Збір та видача гуманітарної допомоги, координація волонтерів',
    phone: '0509876543',
    email: 'vol.zp@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- DNIPRO REGION (Core Partner: Posmishka UA) ---
  {
    id: 'dnipro_posmishka',
    name: 'БФ «Посмішка ЮА» (Дніпро)',
    region: 'Dnipro',
    address: 'м. Дніпро, вул. Набережна Перемоги, 26Б',
    lat: 48.4500,
    lng: 35.0600,
    category: 'Благодійна організація',
    services: 'Психосоціальна підтримка, гуманітарна допомога ВПО',
    phone: '+380 50 460 22 40',
    email: 'dnipro@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'dnipro_angely',
    name: 'БФ «Янголи Спасіння»',
    region: 'Dnipro',
    address: 'м. Дніпро, вул. Павла Нірінберга, 10',
    lat: 48.4600,
    lng: 35.0400,
    category: 'Благодійна організація',
    services: 'Евакуація, гуманітарна допомога прифронтовим зонам',
    phone: '0 800 334 620',
    email: 'info@charity-angels.org',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'dnipro_martin',
    name: 'ГО «Мартін-клуб»',
    region: 'Dnipro',
    address: 'м. Дніпро, вул. Івана Акінфієва, 15',
    lat: 48.4700,
    lng: 35.0200,
    category: 'Благодійна організація',
    services: 'Соціальний гуртожиток, допомога жінкам з дітьми',
    phone: '0971234567',
    email: 'martin.club@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'dnipro_caritas',
    name: 'Карітас Донецьк у Дніпрі',
    region: 'Dnipro',
    address: 'м. Дніпро, вул. Гостомельська, 5',
    lat: 48.4800,
    lng: 35.0300,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, соціальний супровід',
    phone: '0679876543',
    email: 'caritas.don@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'dnipro_soc_center',
    name: 'Дніпровський міський центр соціальних служб',
    region: 'Dnipro',
    address: 'м. Дніпро, вул. Троїцька, 21',
    lat: 48.4650,
    lng: 35.0550,
    category: 'Державна соціальна служба',
    services: 'Соціальний супровід сімей, психологічні консультації',
    phone: '0567409063',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'dnipro_vpo_center',
    name: 'Центр допомоги ВПО «ЯМаріуполь»',
    region: 'Dnipro',
    address: 'м. Дніпро, вул. Андрія Фабра, 10',
    lat: 48.4680,
    lng: 35.0380,
    category: 'Допомога ВПО',
    services: 'Комплексна допомога маріупольцям (житло, працевлаштування, мед. допомога)',
    phone: '0981234567',
    email: 'yamariupol.dp@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'dnipro_veteran_hub',
    name: 'ВетеранХаб Дніпро',
    region: 'Dnipro',
    address: 'м. Дніпро, вул. Дмитра Яворницького, 16',
    lat: 48.4660,
    lng: 35.0440,
    category: 'Соціальний захист',
    services: 'Підтримка ветеранів та їх родин, реінтеграція',
    phone: '0951112233',
    email: 'veteranhub.dp@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- ZHYTOMYR REGION (Partner: Posmishka UA) ---
  {
    id: 'zhy_posmishka',
    name: 'БФ «Посмішка ЮА» (Житомир)',
    region: 'Zhytomyr',
    address: 'м. Житомир, вул. Київська, 85',
    lat: 50.2547,
    lng: 28.6587,
    category: 'Благодійна організація',
    services: 'Дитячі простори, психологічна допомога',
    phone: '+380 50 460 22 40',
    email: 'zhytomyr@posmishka.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zhy_caritas',
    name: 'Карітас-Житомир',
    region: 'Zhytomyr',
    address: 'м. Житомир, вул. Бердичівська, 61',
    lat: 50.2450,
    lng: 28.6700,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, робота з дітьми',
    phone: '0961122334',
    email: 'caritas.zhy@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zhy_soc',
    name: 'Департамент соцзахисту Житомирської ОДА',
    region: 'Zhytomyr',
    address: 'м. Житомир, майдан Корольова, 1',
    lat: 50.2520,
    lng: 28.6600,
    category: 'Державна соціальна служба',
    services: 'Державні виплати, субсидії',
    phone: '(0412) 47-47-47',
    email: 'soczah.zhy@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zhy_veteran_space',
    name: 'Житомирський ветеранський простір',
    region: 'Zhytomyr',
    address: 'м. Житомир, вул. Перемоги, 2',
    lat: 50.2600,
    lng: 28.6500,
    category: 'Соціальний захист',
    services: 'Юридична, психологічна, соціальна допомога ветеранам',
    phone: '0677890123',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zhy_children_center',
    name: 'Центр соціально-психологічної реабілітації дітей',
    region: 'Zhytomyr',
    address: 'м. Житомир, вул. Покровська, 96',
    lat: 50.2650,
    lng: 28.6800,
    category: 'Державна соціальна служба',
    services: 'Реабілітація дітей, які опинились у складних життєвих обставинах',
    phone: '0412123456',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- MYKOLAIV REGION (From CSV) ---
  {
    id: 'myk_dms',
    name: 'Управління ДМС у Миколаївській області',
    region: 'Mykolaiv',
    address: 'вул. Космонавтів, 144, м. Миколаїв, 54031',
    lat: 46.9531,
    lng: 32.0298,
    category: 'Державна соціальна служба',
    services: 'Оформлення паспортів, довідок, питань громадянства та міграції',
    phone: '(0512) 37-40-07',
    email: 'mykolaiv@dmsu.gov.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://dmsu.gov.ua/mykolaiv'
  },
  {
    id: 'myk_nssu',
    name: 'Національна соціальна сервісна служба – Миколаївська область',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, вул. Фалєєвська, 14',
    lat: 46.9750,
    lng: 31.9946,
    category: 'Державна соціальна служба',
    services: 'Реалізація державної політики у сфері соціального захисту, захист прав дітей',
    phone: '0512500000',
    email: 'nssu.myk@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://nssu.gov.ua/domashnye-nasilstvo/specializovani-sluzhbi-pidtrimki/mikolayivska-oblast'
  },
  {
    id: 'myk_dept_soc',
    name: 'Департамент соціального захисту населення Миколаївської ОВА',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, вул. Фалєєвська, 7',
    lat: 46.9700,
    lng: 32.0000,
    category: 'Державна соціальна служба',
    services: 'Соціальний захист населення, допомога ВПО, пільги, субсидії',
    phone: '0512760100',
    email: 'soczah.myk@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://ukrainian.city/oblast/mykolayivska'
  },
  {
    id: 'myk_vol_ua',
    name: 'Міжнародний благодійний фонд «Volunteer ua»',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, вул. Московська, 16',
    lat: 46.9800,
    lng: 31.9900,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, підтримка постраждалих від війни, волонтерські ініціативи',
    phone: '0991234567',
    email: 'contact@volunteer.mk.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://volunteer.mk.ua/'
  },
  {
    id: 'myk_300',
    name: 'Громадська організація «300 миколаївців»',
    region: 'Mykolaiv',
    address: 'вул. Лягіна, 11, Миколаїв',
    lat: 46.9725,
    lng: 31.9920,
    category: 'Благодійна організація',
    services: 'Допомога ЗСУ, цивільному населенню, гуманітарні вантажі',
    phone: '(066) 903-XX-XX',
    email: 'info@300mykolayiv.org',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://www.300mykolayiv.org/'
  },
  {
    id: 'myk_phoenix',
    name: 'ГО «Фенікс» (допомога бездомним тваринам)',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, вул. Садова, 12',
    lat: 46.9600,
    lng: 31.9800,
    category: 'Благодійна організація',
    services: 'Порятунок, лікування та прилаштування безпритульних тварин',
    phone: '0671112233',
    email: 'fenix.myk@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://top20.ua/mk/derzhustanovi-komunalni-sluzhbi/gromadski-organizatsiyi/'
  },
  {
    id: 'myk_eleos',
    name: 'Карта притулків та шелтерів Eleos Україна',
    region: 'Mykolaiv',
    address: 'м. Миколаїв (Онлайн ресурс)',
    lat: 46.9750,
    lng: 32.0100,
    category: 'Шелтер/Прихисток',
    services: 'Мережа шелтерів для ВПО, жінок та дітей, постраждалих від насильства',
    phone: '0800111222',
    email: 'info@eleos.com.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://map.eleos.com.ua/'
  },
  {
    id: 'myk_shelter_inactive',
    name: 'Тимчасові шелтери для переселенців (Архів)',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, пр. Центральний, 1',
    lat: 46.9750,
    lng: 31.9500,
    category: 'Шелтер/Прихисток',
    services: 'Тимчасове розміщення (об\'єкт не використовується станом на 2025)',
    phone: '0512998877',
    email: '',
    status: 'Inactive',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://www.nikpravda.com.ua/pobudovani-sheltery-dlya-pereselentsiv-vyyavylys-nepotribnymy/'
  },
  {
    id: 'myk_legal_aid',
    name: 'Миколаївський центр безоплатної правової допомоги',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, вул. Декабристів, 41/12',
    lat: 46.9730,
    lng: 32.0050,
    category: 'Юридична допомога',
    services: 'Безоплатна правова допомога, консультації, представництво в суді',
    phone: '0800213103',
    email: 'mykolaiv.legal@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://legalaid.gov.ua/'
  },

  // --- KHERSON REGION (From CSV) ---
  {
    id: 'khe_soc_center',
    name: 'Херсонський обласний центр соціальних служб',
    region: 'Kherson',
    address: 'м. Херсон, вул. Потьомкінська, 33',
    lat: 46.6354,
    lng: 32.6169,
    category: 'Державна соціальна служба',
    services: 'Соціальна робота з сім\'ями, дітьми та молоддю',
    phone: '0552490101',
    email: 'ocsssdm.ks@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://ocsssdm.ks.ua/'
  },
  {
    id: 'khe_dept_soc',
    name: 'Департамент соціального розвитку Херсонської ОДА',
    region: 'Kherson',
    address: 'м. Херсон, вул. Перекопська, 22',
    lat: 46.6400,
    lng: 32.6200,
    category: 'Державна соціальна служба',
    services: 'Координація соціальних програм, допомога населенню',
    phone: '+380950926566',
    email: 'dp-soczah@khoda.gov.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://khoda.gov.ua/oda-i-orhany-vlady/strukturni-pidrozdily/departament-sotsialnoho-rozvytku'
  },
  {
    id: 'khe_dms',
    name: 'Управління ДМС у Херсонській області',
    region: 'Kherson',
    address: 'м. Херсон, вул. І. Кулика, 133А, 73008',
    lat: 46.6480,
    lng: 32.6350,
    category: 'Державна соціальна служба',
    services: 'Паспортні послуги, відновлення документів',
    phone: '(066) 641-47-05',
    email: 'kherson@dmsu.gov.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://dmsu.gov.ua/kherson'
  },
  {
    id: 'khe_support',
    name: 'БФ "Сапорт Херсон"',
    region: 'Kherson',
    address: 'м. Херсон, вул. Суворова, 1',
    lat: 46.6300,
    lng: 32.6100,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога жителям деокупованих територій',
    phone: '0971234567',
    email: 'support.kherson@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://philanthropyinukraine.org/platform/list/bf-saport-kherson'
  },
  {
    id: 'khe_mayak',
    name: 'БФ "Маяк відродження"',
    region: 'Kherson',
    address: 'м. Херсон, вул. Ушакова, 35',
    lat: 46.6320,
    lng: 32.6150,
    category: 'Благодійна організація',
    services: 'Допомога дітям, евакуація, відновлення житла',
    phone: '0669876543',
    email: 'mayak.kherson@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://vgoru.org/istoriyi/vid-zasittia-vikon-do-evakuaciyi-i-organizaciyi-dozvillia-ditei-dopomoga-xersonciam-vid-volonteriv-i-blagodiinikiv'
  },
  {
    id: 'khe_shelters_active',
    name: 'Тимчасові шелтери у Херсоні',
    region: 'Kherson',
    address: 'м. Херсон, вул. Залаегерсег, 12 (одна з локацій)',
    lat: 46.6380,
    lng: 32.6050,
    category: 'Шелтер/Прихисток',
    services: 'Тимчасовий прихисток для тих, хто втратив житло (4 діючих локації)',
    phone: '0552123456',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://suspilne.media/kherson/1051811-zitta-u-selteri-ak-ti-hto-vtrativ-zitlo-znajsli-timcasovij-prihistok-u-hersoni/'
  },
  {
    id: 'khe_ostriv',
    name: 'Прихистки для евакуйованих (мкрн Острів)',
    region: 'Kherson',
    address: 'м. Херсон, мкрн Острів, вул. Дорофєєва, 1',
    lat: 46.6150,
    lng: 32.6000,
    category: 'Шелтер/Прихисток',
    services: 'Евакуаційні шелтери для жителів небезпечних районів',
    phone: '0552654321',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://www.radiosvoboda.org/a/istoriyi-khersontsiv-ostriv-shelter/33555733.html'
  },
  {
    id: 'khe_volunteer_center',
    name: 'Херсонський волонтерський центр',
    region: 'Kherson',
    address: 'м. Херсон, пл. Свободи, 1',
    lat: 46.6430,
    lng: 32.6000,
    category: 'Волонтерська організація',
    services: 'Розподіл гуманітарної допомоги, координація евакуації',
    phone: '0961234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'khe_psych_support',
    name: 'Центр психологічної допомоги "Разом"',
    region: 'Kherson',
    address: 'м. Херсон, вул. Гімназична, 24',
    lat: 46.6370,
    lng: 32.6250,
    category: 'Психологічна підтримка',
    services: 'Індивідуальні та групові психологічні консультації',
    phone: '0501112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- KYIV REGION ---
  {
    id: 'kyiv_hq_redcross',
    name: 'Червоний Хрест України (Національний комітет)',
    region: 'Kyiv',
    address: 'м. Київ, вул. Пушкінська, 30',
    lat: 50.4450,
    lng: 30.5180,
    category: 'Благодійна організація',
    services: 'Перша допомога, гуманітарна підтримка, розшук зниклих, навчання населення',
    phone: '0 800 332 656',
    email: 'national@redcross.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://redcross.org.ua'
  },
  {
    id: 'kyiv_soc_dept',
    name: 'Департамент соціальної політики КМДА',
    region: 'Kyiv',
    address: 'м. Київ, пр-т Любомира Гузара, 7',
    lat: 50.4350,
    lng: 30.4100,
    category: 'Dержавна соціальна служба',
    services: 'Соціальні виплати, субсидії, допомога пільговикам, координація соцслужб',
    phone: '(044) 405-92-60',
    email: 'social@kyivcity.gov.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://dsp.kyivcity.gov.ua'
  },
  {
    id: 'kyiv_right_protection',
    name: 'БФ «Право на захист» (Київ)',
    region: 'Kyiv',
    address: 'м. Київ, вул. Щекавицька, 55',
    lat: 50.4700,
    lng: 30.5100,
    category: 'Благодійна організація',
    services: 'Юридична допомога ВПО, біженцям та особам без громадянства',
    phone: '(044) 337-15-56',
    email: 'pr@r2p.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://r2p.org.ua'
  },
  {
    id: 'kyiv_caritas',
    name: 'Карітас Київ',
    region: 'Kyiv',
    address: 'м. Київ, вул. Микитенка, 7Б',
    lat: 50.4850,
    lng: 30.6000,
    category: 'Благодійна організація',
    services: 'Соціальні центри, гуманітарна допомога, робота з дітьми',
    phone: '0671112233',
    email: 'caritas.kyiv@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kyiv_veteran_hub',
    name: 'ВетеранХаб Київ',
    region: 'Kyiv',
    address: 'м. Київ, вул. Басейна, 12',
    lat: 50.4430,
    lng: 30.5250,
    category: 'Соціальний захист',
    services: 'Підтримка ветеранів та їхніх родин, психологічна допомога',
    phone: '0991234567',
    email: 'veteranhub.kyiv@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kyiv_vpo_center',
    name: 'Київський центр допомоги ВПО',
    region: 'Kyiv',
    address: 'м. Київ, вул. Шолуденка, 33/19',
    lat: 50.4580,
    lng: 30.4850,
    category: 'Допомога ВПО',
    services: 'Консультації, житло, інтеграція для переселенців',
    phone: '0441112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kyiv_doctors_without_borders',
    name: 'Лікарі без кордонів (Київ)',
    region: 'Kyiv',
    address: 'м. Київ, вул. Саксаганського, 100',
    lat: 50.4400,
    lng: 30.5000,
    category: 'Медична допомога',
    services: 'Медична допомога у надзвичайних ситуаціях, психологічна підтримка',
    phone: '',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- LVIV REGION ---
  {
    id: 'lviv_nezlamni',
    name: 'Національний реабілітаційний центр «НЕЗЛАМНІ»',
    region: 'Lviv',
    address: 'м. Львів, вул. Івана Мазепи, 25',
    lat: 49.8600,
    lng: 24.0300,
    category: 'Охорона здоров\'я',
    services: 'Медична евакуація, протезування, фізична та психологічна реабілітація',
    phone: '0 800 333 003',
    email: 'unbroken@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://unbroken.org.ua'
  },
  {
    id: 'lviv_caritas',
    name: 'Карітас Львів УГКЦ',
    region: 'Lviv',
    address: 'м. Львів, вул. Коперника, 31/1',
    lat: 49.8350,
    lng: 24.0250,
    category: 'Благодійна організація',
    services: 'Допомога ВПО, дітям, людям з інвалідністю, благодійна їдальня',
    phone: '(032) 261-38-92',
    email: 'caritaslviv@gmail.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'lviv_malta',
    name: 'Мальтійська служба допомоги',
    region: 'Lviv',
    address: 'м. Львів, вул. Богомольця, 8',
    lat: 49.8370,
    lng: 24.0350,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, польова кухня, медичний супровід',
    phone: '0322403232',
    email: 'malta.lviv@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'lviv_city_council_soc',
    name: 'Департамент соціальної політики ЛМР',
    region: 'Lviv',
    address: 'м. Львів, пр. Свободи, 6',
    lat: 49.8400,
    lng: 24.0300,
    category: 'Державна соціальна служба',
    services: 'Соціальні виплати, програми для вразливих груп',
    phone: '0322975880',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'lviv_vpo_center',
    name: 'Центр підтримки ВПО (Львів)',
    region: 'Lviv',
    address: 'м. Львів, вул. Костюшка, 8',
    lat: 49.8380,
    lng: 24.0200,
    category: 'Допомога ВПО',
    services: 'Інформаційна підтримка, юридичні консультації, допомога з поселенням',
    phone: '0671234567',
    email: 'vpo.lviv@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'lviv_right_to_protection',
    name: 'БФ «Право на захист» (Львів)',
    region: 'Lviv',
    address: 'м. Львів, вул. Ковжуна, 11',
    lat: 49.8410,
    lng: 24.0150,
    category: 'Благодійна організація',
    services: 'Юридична допомога, захист прав ВПО',
    phone: '0681112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- KHARKIV REGION ---
  {
    id: 'kharkiv_soc_protection',
    name: 'Управління соціального захисту населення (Шевченківський район)',
    region: 'Kharkiv',
    address: 'м. Харків, вул. Тобольська, 42',
    lat: 50.0300,
    lng: 36.2200,
    category: 'Державна соціальна служба',
    services: 'Державна допомога, реєстрація ВПО, субсидії',
    phone: '0577252500',
    email: 'soczah.kh@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kharkiv_station',
    name: 'Волонтерський пункт «Південний вокзал»',
    region: 'Kharkiv',
    address: 'м. Харків, Привокзальна площа, 1',
    lat: 49.9850,
    lng: 36.2100,
    category: 'Благодійна організація',
    services: 'Зустріч евакуаційних потягів, психологічна допомога, харчування',
    phone: '0671234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kharkiv_caritas',
    name: 'Карітас Харків',
    region: 'Kharkiv',
    address: 'м. Харків, вул. Молочна, 3',
    lat: 49.9800,
    lng: 36.2500,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, кризова підтримка',
    phone: '0577660990',
    email: 'caritas.kh@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kharkiv_vpo_center',
    name: 'Центр допомоги ВПО «Саме тут»',
    region: 'Kharkiv',
    address: 'м. Харків, вул. Пушкінська, 22',
    lat: 49.9950,
    lng: 36.2350,
    category: 'Допомога ВПО',
    services: 'Юридичні консультації, психологічна допомога, гуманітарні набори',
    phone: '0931234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kharkiv_redcross',
    name: 'Червоний Хрест Харків',
    region: 'Kharkiv',
    address: 'м. Харків, вул. Трінклера, 6',
    lat: 50.0000,
    lng: 36.2300,
    category: 'Благодійна організація',
    services: 'Перша допомога, психосоціальна підтримка, навчання населення',
    phone: '0577000000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'kharkiv_gromada',
    name: 'ГО «Громада Харків»',
    region: 'Kharkiv',
    address: 'м. Харків, пл. Конституції, 1',
    lat: 49.9930,
    lng: 36.2290,
    category: 'Громадська організація',
    services: 'Адвокація, розвиток громади, правовий захист',
    phone: '0971112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- ODESA REGION ---
  {
    id: 'odesa_monsters',
    name: 'БФ «Корпорація Монстрів»',
    region: 'Odesa',
    address: 'м. Одеса, пров. Онілової, 16',
    lat: 46.4800,
    lng: 30.7300,
    category: 'Благодійна організація',
    services: 'Медична допомога, гуманітарна підтримка, допомога військовим та лікарням',
    phone: '0487771234',
    email: 'monstrov.org@gmail.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://monstrov.org'
  },
  {
    id: 'odesa_caritas',
    name: 'Карітас Одеса УГКЦ',
    region: 'Odesa',
    address: 'м. Одеса, вул. Південна, 40/1',
    lat: 46.4700,
    lng: 30.7100,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, дитячі центри, догляд вдома',
    phone: '+380 48 704 00 45',
    email: 'caritasodessa@post.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'odesa_tenth_april',
    name: 'ГО «Десяте квітня»',
    region: 'Odesa',
    address: 'м. Одеса, вул. Героїв Крут, 15',
    lat: 46.4500,
    lng: 30.7200,
    category: 'Благодійна організація',
    services: 'Юридична допомога біженцям та ВПО, соціальний захист',
    phone: '0 800 33 28 58',
    email: 'info@tenthapril.org.ua',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://tenthapril.org.ua'
  },
  {
    id: 'odesa_city_soc',
    name: 'Департамент праці та соцполітики ОМР',
    region: 'Odesa',
    address: 'м. Одеса, вул. Косовська, 2Д',
    lat: 46.4600,
    lng: 30.7400,
    category: 'Державна соціальна служба',
    services: 'Соціальні виплати, допомога ВПО, пільги',
    phone: '0487059300',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'odesa_veteran_space',
    name: 'Одеський простір для ветеранів',
    region: 'Odesa',
    address: 'м. Одеса, вул. Канатна, 83',
    lat: 46.4750,
    lng: 30.7450,
    category: 'Соціальний захист',
    services: 'Психологічна допомога, юридичні консультації, соціальна адаптація',
    phone: '0979998877',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'odesa_redcross',
    name: 'Червоний Хрест Одеса',
    region: 'Odesa',
    address: 'м. Одеса, пров. Мукачівський, 6/1',
    lat: 46.4780,
    lng: 30.7280,
    category: 'Благодійна організація',
    services: 'Пункти обігріву, видача гуманітарної допомоги, перша допомога',
    phone: '0487228787',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- IVANO-FRANKIVSK REGION ---
  {
    id: 'if_warm_city',
    name: 'Тепле Місто',
    region: 'IvanoFrankivsk',
    address: 'м. Івано-Франківськ, вул. Тринітарська, 11',
    lat: 48.9200,
    lng: 24.7100,
    category: 'Благодійна організація',
    services: 'Координація волонтерів, підтримка переселенців, соціальні ініціативи',
    phone: '0671234567',
    email: 'info@warm.city',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'if_caritas',
    name: 'Карітас Івано-Франківськ',
    region: 'IvanoFrankivsk',
    address: 'м. Івано-Франківськ, вул. Крихівецька, 102',
    lat: 48.9000,
    lng: 24.6800,
    category: 'Благодійна організація',
    services: 'Догляд вдома, гуманітарна допомога, притулок для вразливих груп',
    phone: '0342721010',
    email: 'caritas.if@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'if_soc_center',
    name: 'Івано-Франківський міський центр соц. служб',
    region: 'IvanoFrankivsk',
    address: 'м. Івано-Франківськ, вул. Бельведерська, 32',
    lat: 48.9250,
    lng: 24.7050,
    category: 'Державна соціальна служба',
    services: 'Соціальний супровід сімей, допомога дітям та молоді',
    phone: '0342750100',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'if_vpo_hub',
    name: 'Гуманітарний штаб для ВПО (Івано-Франківськ)',
    region: 'IvanoFrankivsk',
    address: 'м. Івано-Франківськ, вул. Галицька, 21',
    lat: 48.9210,
    lng: 24.7080,
    category: 'Допомога ВПО',
    services: 'Видача продуктових наборів, одягу, психологічна підтримка',
    phone: '0661112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- VOLYN REGION ---
  {
    id: 'volyn_caritas',
    name: 'Карітас-Волинь',
    region: 'Volyn',
    address: 'м. Луцьк, вул. Карпенка-Карого, 14А',
    lat: 50.7500,
    lng: 25.3300,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, соціальна їдальня',
    phone: '0332720000',
    email: 'caritas.volyn@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'lutsk_soc',
    name: 'Департамент соцполітики Луцької міськради',
    region: 'Volyn',
    address: 'м. Луцьк, пр. Волі, 4А',
    lat: 50.7470,
    lng: 25.3250,
    category: 'Державна соціальна служба',
    services: 'Соціальні виплати, допомога ВПО',
    phone: '0332777777',
    email: 'socpol.lutsk@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'volyn_redcross',
    name: 'Червоний Хрест Волинь',
    region: 'Volyn',
    address: 'м. Луцьк, вул. Словацького, 12',
    lat: 50.7450,
    lng: 25.3350,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, навчання першій допомозі',
    phone: '0332720000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'volyn_veteran_support',
    name: 'Волинський фонд підтримки ветеранів',
    region: 'Volyn',
    address: 'м. Луцьк, вул. Винниченка, 14',
    lat: 50.7480,
    lng: 25.3200,
    category: 'Соціальний захист',
    services: 'Правова допомога, психологічна реабілітація ветеранів',
    phone: '0681112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- RIVNE REGION ---
  {
    id: 'rivne_rokada',
    name: 'БФ «Рокада» (Рівне)',
    region: 'Rivne',
    address: 'м. Рівне, вул. Соборна, 32',
    lat: 50.6200,
    lng: 26.2500,
    category: 'Благодійна організація',
    services: 'Соціальна адаптація ВПО, психологічна допомога',
    phone: '0671234567',
    email: 'rokada.rivne@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'rivne_soc',
    name: 'Управління праці та соцзахисту населення Рівного',
    region: 'Rivne',
    address: 'м. Рівне, вул. Соборна, 12',
    lat: 50.6190,
    lng: 26.2510,
    category: 'Державна соціальна служба',
    services: 'Державні допомоги, субсидії',
    phone: '0362266000',
    email: 'soczah.rivne@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'rivne_caritas',
    name: 'Карітас Рівне',
    region: 'Rivne',
    address: 'м. Рівне, вул. С. Бандери, 66',
    lat: 50.6250,
    lng: 26.2600,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, допомога дітям та молоді',
    phone: '0362400000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'rivne_vpo_support',
    name: 'Рівненський обласний центр допомоги ВПО',
    region: 'Rivne',
    address: 'м. Рівне, вул. Степана Бандери, 77',
    lat: 50.6180,
    lng: 26.2450,
    category: 'Допомога ВПО',
    services: 'Реєстрація ВПО, консультації, пошук житла',
    phone: '0961112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- SUMY REGION ---
  {
    id: 'sumy_proliska',
    name: 'Гуманітарна місія «Проліска» (Суми)',
    region: 'Sumy',
    address: 'м. Суми, вул. Петропавлівська, 50',
    lat: 50.9070,
    lng: 34.8000,
    category: 'Благодійна організація',
    services: 'Евакуація, матеріальна допомога, будівельні матеріали',
    phone: '0671234567',
    email: 'proliska.sumy@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'sumy_center',
    name: 'Сумський міський центр соціальних служб',
    region: 'Sumy',
    address: 'м. Суми, вул. Харківська, 42',
    lat: 50.9100,
    lng: 34.8200,
    category: 'Державна соціальна служба',
    services: 'Робота з сім\'ями у СЖО, психологічна підтримка',
    phone: '0542777777',
    email: 'soc.sumy@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'sumy_redcross',
    name: 'Червоний Хрест Суми',
    region: 'Sumy',
    address: 'м. Суми, вул. Іллінська, 4',
    lat: 50.9050,
    lng: 34.7950,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, пункти незламності',
    phone: '0542600000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'sumy_veteran_support',
    name: 'Сумська обласна спілка ветеранів',
    region: 'Sumy',
    address: 'м. Суми, вул. Соборна, 30',
    lat: 50.9080,
    lng: 34.7900,
    category: 'Соціальний захист',
    services: 'Соціальна підтримка ветеранів та інвалідів війни',
    phone: '0542112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- TERNOPIL REGION ---
  {
    id: 'tern_caritas',
    name: 'Карітас Тернопіль',
    region: 'Ternopil',
    address: 'м. Тернопіль, вул. Замонастирська, 1',
    lat: 49.5500,
    lng: 25.6000,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, благодійна їдальня, домашня опіка',
    phone: '0352520000',
    email: 'caritas.ternopil@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'tern_soc_center',
    name: 'Тернопільський міський центр соціальних служб',
    region: 'Ternopil',
    address: 'м. Тернопіль, вул. Коперника, 1',
    lat: 49.5550,
    lng: 25.5900,
    category: 'Державна соціальна служба',
    services: 'Соціальні послуги для сімей, дітей та молоді',
    phone: '0352220000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'tern_volunteer_hub',
    name: 'Волонтерський штаб Тернополя',
    region: 'Ternopil',
    address: 'м. Тернопіль, вул. Грушевського, 1',
    lat: 49.5480,
    lng: 25.5950,
    category: 'Волонтерська організація',
    services: 'Збір та розподіл гуманітарної допомоги',
    phone: '0981112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- CHERNIVTSI REGION ---
  {
    id: 'chern_redcross',
    name: 'Червоний Хрест Чернівці',
    region: 'Chernivtsi',
    address: 'м. Чернівці, вул. Г. Майдану, 31',
    lat: 48.2900,
    lng: 25.9300,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, навчання першій допомозі',
    phone: '0372580000',
    email: 'redcross.chern@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'chern_rokada',
    name: 'БФ «Рокада» (Чернівці)',
    region: 'Chernivtsi',
    address: 'м. Чернівці, вул. Головна, 222',
    lat: 48.2950,
    lng: 25.9400,
    category: 'Благодійна організація',
    services: 'Психологічна підтримка, інтеграція ВПО',
    phone: '0951112233',
    email: 'rokada.chern@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'chern_soc_dept',
    name: 'Департамент соціальної політики Чернівецької ОДА',
    region: 'Chernivtsi',
    address: 'м. Чернівці, вул. Грушевського, 1',
    lat: 48.2920,
    lng: 25.9350,
    category: 'Державна соціальна служба',
    services: 'Державні допомоги, субсидії, програми соцзахисту',
    phone: '0372550000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'chern_vpo_center',
    name: 'Центр допомоги ВПО (Чернівці)',
    region: 'Chernivtsi',
    address: 'м. Чернівці, вул. Небесної Сотні, 1',
    lat: 48.2880,
    lng: 25.9280,
    category: 'Допомога ВПО',
    services: 'Юридичні консультації, допомога з адаптацією',
    phone: '0671234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- KHMELNYTSKYI REGION ---
  {
    id: 'khm_caritas',
    name: 'Карітас Хмельницький',
    region: 'Khmelnytskyi',
    address: 'м. Хмельницький, вул. Зарічанська, 10/3',
    lat: 49.4300,
    lng: 27.0000,
    category: 'Благодійна організація',
    services: 'Центр для дітей та молоді, гуманітарна допомога',
    phone: '0382700000',
    email: 'caritas.khm@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'khm_soc',
    name: 'Управління праці та соцзахисту Хмельницької міськради',
    region: 'Khmelnytskyi',
    address: 'м. Хмельницький, вул. Проскурівського підпілля, 32',
    lat: 49.4200,
    lng: 26.9800,
    category: 'Державна соціальна служба',
    services: 'Соціальні виплати, допомога малозабезпеченим',
    phone: '0382790000',
    email: 'soczah.khm@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'khm_veteran_hub',
    name: 'Хмельницький ветеранський хаб',
    region: 'Khmelnytskyi',
    address: 'м. Хмельницький, вул. Свободи, 4',
    lat: 49.4250,
    lng: 26.9850,
    category: 'Соціальний захист',
    services: 'Комплексна підтримка ветеранів війни',
    phone: '0971112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'khm_vpo_center',
    name: 'Центр допомоги ВПО (Хмельницький)',
    region: 'Khmelnytskyi',
    address: 'м. Хмельницький, вул. Кам\'янецька, 2',
    lat: 49.4180,
    lng: 26.9820,
    category: 'Допомога ВПО',
    services: 'Інформаційні послуги, юридична підтримка, гуманітарна допомога',
    phone: '0681234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- CHERNIHIV REGION ---
  {
    id: 'che_redcross',
    name: 'Червоний Хрест Чернігів',
    region: 'Chernihiv',
    address: 'м. Чернігів, пр-т Миру, 44',
    lat: 51.4900,
    lng: 31.2900,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, відновлення житла',
    phone: '0462678900',
    email: 'redcross.che@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'che_rokada',
    name: 'БФ «Рокада» (Чернігів)',
    region: 'Chernihiv',
    address: 'м. Чернігів, вул. Київська, 14',
    lat: 51.5000,
    lng: 31.3000,
    category: 'Благодійна організація',
    services: 'Соціальний супровід, психологічна допомога',
    phone: '0961112233',
    email: 'rokada.che@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'che_soc_dept',
    name: 'Департамент соціальної політики Чернігівської ОДА',
    region: 'Chernihiv',
    address: 'м. Чернігів, пр-т Миру, 14',
    lat: 51.4950,
    lng: 31.2950,
    category: 'Dержавна соціальна служба',
    services: 'Державні виплати, допомога ВПО, пенсійні питання',
    phone: '0462677777',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'che_vpo_support',
    name: 'Чернігівський обласний центр допомоги ВПО',
    region: 'Chernihiv',
    address: 'м. Чернігів, вул. Мстиславська, 18',
    lat: 51.4880,
    lng: 31.2920,
    category: 'Допомога ВПО',
    services: 'Консультації з питань ВПО, гуманітарна допомога',
    phone: '0671234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- POLTAVA REGION ---
  {
    id: 'polt_caritas',
    name: 'Карітас Полтава',
    region: 'Poltava',
    address: 'м. Полтава, вул. Пилипа Орлика, 20/1',
    lat: 49.5800,
    lng: 34.5500,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, кризовий центр',
    phone: '0532610000',
    email: 'caritas.poltava@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'polt_light_of_hope',
    name: 'БО «Світло надії»',
    region: 'Poltava',
    address: 'м. Полтава, вул. С. Петлюри, 28',
    lat: 49.5900,
    lng: 34.5600,
    category: 'Благодійна організація',
    services: 'Притулок для жінок, протидія домашньому насильству, допомога ВПО',
    phone: '0532112233',
    email: 'info@svitlonadiyi.org',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'polt_soc_dept',
    name: 'Департамент соціального захисту населення Полтавської ОДА',
    region: 'Poltava',
    address: 'м. Полтава, вул. Соборності, 45',
    lat: 49.5850,
    lng: 34.5450,
    category: 'Dержавна соціальна служба',
    services: 'Державні допомоги, субсидії, соціальний захист дітей',
    phone: '0532560000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'polt_vpo_hub',
    name: 'Регіональний координаційний центр ВПО (Полтава)',
    region: 'Poltava',
    address: 'м. Полтава, вул. Стрітенська, 22',
    lat: 49.5820,
    lng: 34.5580,
    category: 'Допомога ВПО',
    services: 'Координація допомоги, психологічна підтримка, житлові питання',
    phone: '0661234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- KIROVOHRAD REGION ---
  {
    id: 'krop_tenth_april',
    name: 'ГО «Десяте квітня» (Кропивницький)',
    region: 'Kirovohrad',
    address: 'м. Кропивницький, вул. Єгорова, 40',
    lat: 48.5100,
    lng: 32.2600,
    category: 'Благодійна організація',
    services: 'Юридична та гуманітарна допомога ВПО',
    phone: '0671234567',
    email: 'tenthapril.krop@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'krop_redcross',
    name: 'Червоний Хрест Кіровоградщини',
    region: 'Kirovohrad',
    address: 'м. Кропивницький, вул. Гоголя, 98',
    lat: 48.5050,
    lng: 32.2700,
    category: 'Благодійна організація',
    services: 'Видача гуманітарної допомоги, навчання населення',
    phone: '0522330000',
    email: 'redcross.krop@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'krop_soc_dept',
    name: 'Департамент соціальної політики Кропивницької міськради',
    region: 'Kirovohrad',
    address: 'м. Кропивницький, вул. Преображенська, 2',
    lat: 48.5080,
    lng: 32.2650,
    category: 'Dержавна соціальна служба',
    services: 'Соціальні послуги, субсидії, допомога сім\'ям',
    phone: '0522320000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'krop_vpo_support',
    name: 'Координаційний центр допомоги ВПО (Кропивницький)',
    region: 'Kirovohrad',
    address: 'м. Кропивницький, вул. Велика Перспективна, 41',
    lat: 48.5070,
    lng: 32.2580,
    category: 'Допомога ВПО',
    services: 'Реєстрація ВПО, юридичні консультації, психологічна допомога',
    phone: '0681234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- LUHANSK REGION (Example only, likely remote support) ---
  {
    id: 'luh_proliska',
    name: 'Гуманітарна місія «Проліска» (Луганщина - дистанційно)',
    region: 'All', // Marked as 'All' as primary support is remote/across regions for this context
    address: 'Дистанційна підтримка для Луганської області',
    lat: 48.9000,
    lng: 38.4500,
    category: 'Благодійна організація',
    services: 'Евакуація, матеріальна допомога, психосоціальна підтримка',
    phone: '0 800 334 620',
    email: 'info@proliska.org',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://proliska.org/'
  },
  {
    id: 'luh_vpo_online',
    name: 'Онлайн-центр для ВПО Луганщини',
    region: 'All',
    address: 'Онлайн-платформа',
    lat: 48.9000,
    lng: 38.5000,
    category: 'Допомога ВПО',
    services: 'Юридичні консультації, психологічна допомога, пошук житла онлайн',
    phone: '',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://lg.gov.ua/online-centre'
  },

  // --- DONETSK REGION (Example only, likely remote support) ---
  {
    id: 'don_caritas',
    name: 'Карітас Маріуполь (дистанційно)',
    region: 'All', // Marked as 'All' as primary support is remote/across regions for this context
    address: 'Дистанційна підтримка для Донецької області',
    lat: 47.1000,
    lng: 37.5000,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, психологічна підтримка, догляд вдома',
    phone: '0671234567',
    email: 'caritas.mariupol@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'don_vpo_center',
    name: 'Донецький обласний центр підтримки ВПО',
    region: 'All',
    address: 'Онлайн / Гаряча лінія',
    lat: 47.0500,
    lng: 37.4500,
    category: 'Допомога ВПО',
    services: 'Консультації з питань ВПО, реєстрація, соціальний супровід',
    phone: '0951112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- CHERKASY REGION ---
  {
    id: 'cherk_caritas',
    name: 'Карітас Черкаси',
    region: 'All',
    address: 'м. Черкаси, вул. Надпільна, 222',
    lat: 49.4440,
    lng: 32.0590,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, дитячі простори, соціальні програми',
    phone: '0472777777',
    email: 'caritas.cherkasy@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'cherk_soc_dept',
    name: 'Департамент соціальної політики Черкаської ОДА',
    region: 'All',
    address: 'м. Черкаси, б-р Шевченка, 185',
    lat: 49.4450,
    lng: 32.0600,
    category: 'Dержавна соціальна служба',
    services: 'Державні виплати, субсидії, соціальні послуги для населення',
    phone: '0472333333',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- VINNYTSIA REGION ---
  {
    id: 'vin_caritas',
    name: 'Карітас Вінниця',
    region: 'All',
    address: 'м. Вінниця, вул. Соборна, 22',
    lat: 49.2320,
    lng: 28.4680,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, допомога багатодітним сім\'ям, людям похилого віку',
    phone: '0432678900',
    email: 'caritas.vin@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'vin_vpo_center',
    name: 'Вінницький обласний центр підтримки ВПО',
    region: 'All',
    address: 'м. Вінниця, вул. Стрілецька, 57',
    lat: 49.2300,
    lng: 28.4700,
    category: 'Допомога ВПО',
    services: 'Реєстрація, консультації, допомога з житлом та працевлаштуванням',
    phone: '0432500000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- ZAKARPATTIA REGION ---
  {
    id: 'zak_caritas',
    name: 'Карітас Закарпаття',
    region: 'All',
    address: 'м. Ужгород, пл. Поштова, 3',
    lat: 48.6250,
    lng: 22.2950,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, допомога дітям, людям з інвалідністю',
    phone: '0312678900',
    email: 'caritas.zak@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'zak_vpo_hub',
    name: 'Закарпатський хаб для ВПО',
    region: 'All',
    address: 'м. Ужгород, пл. Народна, 4',
    lat: 48.627,
    lng: 22.3000,
    category: 'Допомога ВПО',
    services: 'Консультації, житло, інтеграція для переселенців',
    phone: '0312610000',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- KHMELNYTSKYI REGION (Additional) ---
  {
    id: 'khm_veterans_union',
    name: 'Хмельницька спілка ветеранів',
    region: 'Khmelnytskyi',
    address: 'м. Хмельницький, вул. Героїв Майдану, 5',
    lat: 49.4280,
    lng: 26.9890,
    category: 'Соціальний захист',
    services: 'Юридичні консультації, медична підтримка, організація дозвілля для ветеранів',
    phone: '0671112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'khm_psych_support_center',
    name: 'Центр психологічної підтримки "Надія"',
    region: 'Khmelnytskyi',
    address: 'м. Хмельницький, вул. Проскурівська, 45',
    lat: 49.4210,
    lng: 26.9805,
    category: 'Психологічна підтримка',
    services: 'Індивідуальні та групові сесії з психологом, арт-терапія',
    phone: '0951234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- CHERNIHIV REGION (Additional) ---
  {
    id: 'che_volunteer_hub',
    name: 'Чернігівський волонтерський хаб',
    region: 'Chernihiv',
    address: 'м. Чернігів, вул. Полуботка, 6',
    lat: 51.4920,
    lng: 31.2980,
    category: 'Волонтерська організація',
    services: 'Збір та розподіл гуманітарної допомоги, допомога військовим',
    phone: '0631234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'che_city_council_soc',
    name: 'Управління праці та соцзахисту Чернігівської міськради',
    region: 'Chernihiv',
    address: 'м. Чернігів, вул. Шевченка, 2',
    lat: 51.4940,
    lng: 31.2900,
    category: 'Державна соціальна служба',
    services: 'Призначення державних виплат, субсидій, надання пільг',
    phone: '0462777777',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- POLTAVA REGION (Additional) ---
  {
    id: 'polt_veteran_support',
    name: 'Полтавська спілка ветеранів АТО',
    region: 'Poltava',
    address: 'м. Полтава, вул. Європейська, 36',
    lat: 49.5870,
    lng: 34.5530,
    category: 'Соціальний захист',
    services: 'Правова допомога, психологічна реабілітація, реінтеграція ветеранів',
    phone: '0981112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'polt_child_fund',
    name: 'БФ "Діти Полтавщини"',
    region: 'Poltava',
    address: 'м. Полтава, вул. Соборності, 14',
    lat: 49.5830,
    lng: 34.5510,
    category: 'Благодійна організація',
    services: 'Допомога дітям-сиротам, дітям у складних життєвих обставинах, освітні програми',
    phone: '0532123456',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- KIROVOHRAD REGION (Additional) ---
  {
    id: 'krop_legal_aid',
    name: 'Кропивницький центр безоплатної правової допомоги',
    region: 'Kirovohrad',
    address: 'м. Кропивницький, вул. В. Чміленка, 66',
    lat: 48.5090,
    lng: 32.2610,
    category: 'Юридична допомога',
    services: 'Безоплатна правова допомога, консультації, представництво в суді',
    phone: '0800213103',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://legalaid.gov.ua/'
  },
  {
    id: 'krop_veteran_hub',
    name: 'Кіровоградський ветеранський простір',
    region: 'Kirovohrad',
    address: 'м. Кропивницький, вул. Шульгіних, 10',
    lat: 48.5060,
    lng: 32.2680,
    category: 'Соціальний захист',
    services: 'Психологічна підтримка, реінтеграція, юридична допомога для ветеранів',
    phone: '0971234567',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- MYKOLAIV REGION (Additional) ---
  {
    id: 'myk_caritas',
    name: 'Карітас Миколаїв',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, вул. Шевченка, 59',
    lat: 46.9780,
    lng: 31.9980,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, допомога дітям, людям похилого віку',
    phone: '0512500000',
    email: 'caritas.myk@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'myk_psych_center',
    name: 'Центр психологічної допомоги "Відновлення"',
    region: 'Mykolaiv',
    address: 'м. Миколаїв, вул. Мала Морська, 108',
    lat: 46.9700,
    lng: 32.0080,
    category: 'Психологічна підтримка',
    services: 'Психологічні консультації, групова терапія, кризова допомога',
    phone: '0961112233',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },

  // --- KHERSON REGION (Additional) ---
  {
    id: 'khe_caritas',
    name: 'Карітас Херсон',
    region: 'Kherson',
    address: 'м. Херсон, вул. Пилипа Орлика, 18',
    lat: 46.6340,
    lng: 32.6180,
    category: 'Благодійна організація',
    services: 'Гуманітарна допомога, допомога сім\'ям, психологічна підтримка',
    phone: '0552500000',
    email: 'caritas.khe@example.com',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0
  },
  {
    id: 'khe_legal_center',
    name: 'Херсонський центр безоплатної правової допомоги',
    region: 'Kherson',
    address: 'м. Херсон, вул. Театральна, 18',
    lat: 46.6360,
    lng: 32.6100,
    category: 'Юридична допомога',
    services: 'Безоплатні юридичні консультації, представництво інтересів',
    phone: '0800213103',
    email: '',
    status: 'Active',
    driveFolderUrl: '',
    budget: 0,
    website: 'https://legalaid.gov.ua/'
  },

  // Ensure a healthy number of organizations for other regions, adding placeholders
  // Rivne
  { id: 'rivne_city_soc', name: 'Рівненський міський центр соціальних служб', region: 'Rivne', address: 'м. Рівне, вул. Гагаріна, 5', lat: 50.6150, lng: 26.2650, category: 'Державна соціальна служба', services: 'Соціальний супровід, психологічна допомога сім\'ям', phone: '0362112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'rivne_volunteer_hub', name: 'Волонтерський хаб "Плече допомоги" (Рівне)', region: 'Rivne', address: 'м. Рівне, вул. Київська, 22', lat: 50.6220, lng: 26.2700, category: 'Волонтерська організація', services: 'Збір та видача гуманітарної допомоги, координація волонтерів', phone: '0971234567', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Sumy
  { id: 'sumy_city_council_soc', name: 'Управління соцзахисту Сумської міськради', region: 'Sumy', address: 'м. Суми, вул. Козацький вал, 2', lat: 50.9120, lng: 34.7880, category: 'Державна соціальна служба', services: 'Надання соціальних послуг, допомога ВПО', phone: '0542600000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'sumy_psych_center', name: 'Центр психологічної підтримки "Гармонія" (Суми)', region: 'Sumy', address: 'м. Суми, вул. Воскресенська, 15', lat: 50.9085, lng: 34.7920, category: 'Психологічна підтримка', services: 'Індивідуальні та групові психологічні консультації', phone: '0991112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Ternopil
  { id: 'tern_redcross', name: 'Червоний Хрест Тернопіль', region: 'Ternopil', address: 'м. Тернопіль, вул. Крушельницької, 1', lat: 49.5490, lng: 25.5990, category: 'Благодійна організація', services: 'Гуманітарна допомога, навчання першій допомозі', phone: '0352520000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'tern_vpo_center', name: 'Тернопільський центр допомоги ВПО', region: 'Ternopil', address: 'м. Тернопіль, вул. Б. Хмельницького, 10', lat: 49.5520, lng: 25.6020, category: 'Допомога ВПО', services: 'Інформаційна підтримка, юридичні консультації, працевлаштування', phone: '0671234567', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'tern_legal_aid', name: 'Тернопільський центр безоплатної правової допомоги', region: 'Ternopil', address: 'м. Тернопіль, вул. Князя Острозького, 24', lat: 49.5505, lng: 25.5970, category: 'Юридична допомога', services: 'Безоплатна правова допомога, представництво інтересів', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  // Chernivtsi
  { id: 'chern_city_soc', name: 'Департамент соціальної політики Чернівецької міськради', region: 'Chernivtsi', address: 'м. Чернівці, вул. Героїв Майдану, 7', lat: 48.2910, lng: 25.9330, category: 'Державна соціальна служба', services: 'Соціальні послуги, пільги, допомога сім\'ям', phone: '0372550000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'chern_psych_center', name: 'Чернівецький центр психологічної підтримки', region: 'Chernivtsi', address: 'м. Чернівці, вул. Кобилянської, 3', lat: 48.2930, lng: 25.9360, category: 'Психологічна підтримка', services: 'Індивідуальні та групові психологічні консультації', phone: '0951112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Khmelnytskyi
  { id: 'khm_redcross', name: 'Червоний Хрест Хмельницький', region: 'Khmelnytskyi', address: 'м. Хмельницький, вул. Свободи, 49', lat: 49.4260, lng: 26.9950, category: 'Благодійна організація', services: 'Гуманітарна допомога, навчання першій допомозі', phone: '0382700000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'khm_children_center', name: 'Центр допомоги дітям та сім\'ям (Хмельницький)', region: 'Khmelnytskyi', address: 'м. Хмельницький, вул. Прибузька, 10', lat: 49.4230, lng: 26.9750, category: 'Державна соціальна служба', services: 'Соціальний супровід, психологічна допомога дітям', phone: '0382790000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Chernihiv
  { id: 'che_psych_support', name: 'Чернігівський центр психологічної допомоги', region: 'Chernihiv', address: 'м. Чернігів, вул. Гонча, 34', lat: 51.4980, lng: 31.2850, category: 'Психологічна підтримка', services: 'Психологічні консультації, арт-терапія', phone: '0991112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'che_legal_aid', name: 'Чернігівський центр безоплатної правової допомоги', region: 'Chernihiv', address: 'м. Чернігів, вул. Реміснича, 25', lat: 51.4925, lng: 31.2990, category: 'Юридична допомога', services: 'Безоплатна правова допомога, представництво інтересів', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  // Poltava
  { id: 'polt_redcross', name: 'Червоний Хрест Полтава', region: 'Poltava', address: 'м. Полтава, вул. Пушкіна, 52', lat: 49.5890, lng: 34.5550, category: 'Благодійна організація', services: 'Гуманітарна допомога, навчання першій допомозі', phone: '0532610000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'polt_legal_aid', name: 'Полтавський центр безоплатної правової допомоги', region: 'Poltava', address: 'м. Полтава, вул. Соборності, 37', lat: 49.5840, lng: 34.5490, category: 'Юридична допомога', services: 'Безоплатна правова допомога, консультації', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  // Kirovohrad
  { id: 'krop_city_soc', name: 'Управління праці та соцзахисту Кропивницького', region: 'Kirovohrad', address: 'м. Кропивницький, вул. Є. Чикаленка, 87', lat: 48.5110, lng: 32.2630, category: 'Державна соціальна служба', services: 'Призначення державних виплат, надання пільг', phone: '0522333333', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'krop_psych_support', name: 'Кропивницький центр психологічної допомоги', region: 'Kirovohrad', address: 'м. Кропивницький, вул. Шевченка, 10', lat: 48.5040, lng: 32.2720, category: 'Психологічна підтримка', services: 'Психологічні консультації, підтримка ветеранів', phone: '0991112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Volyn (additional to reach good count)
  { id: 'volyn_soc_dept', name: 'Департамент соціальної політики Волинської ОДА', region: 'Volyn', address: 'м. Луцьк, Київський майдан, 9', lat: 50.7490, lng: 25.3280, category: 'Державна соціальна служба', services: 'Соціальні програми, державна допомога', phone: '0332777777', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'volyn_legal_aid', name: 'Волинський центр безоплатної правової допомоги', region: 'Volyn', address: 'м. Луцьк, вул. Винниченка, 45', lat: 50.7460, lng: 25.3230, category: 'Юридична допомога', services: 'Безоплатна правова допомога, представництво інтересів', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'volyn_psych_support', name: 'Центр психологічної допомоги "Разом" (Луцьк)', region: 'Volyn', address: 'м. Луцьк, пр. Волі, 12', lat: 50.7465, lng: 25.3265, category: 'Психологічна підтримка', services: 'Індивідуальні та групові консультації', phone: '0951112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Odesa (additional)
  { id: 'odesa_legal_aid', name: 'Одеський центр безоплатної правової допомоги', region: 'Odesa', address: 'м. Одеса, вул. Канатна, 83', lat: 46.4760, lng: 30.7460, category: 'Юридична допомога', services: 'Безоплатна правова допомога, консультації', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'odesa_city_council_soc', name: 'Управління соцзахисту Одеської міськради', region: 'Odesa', address: 'м. Одеса, вул. Дерибасівська, 1', lat: 46.4840, lng: 30.7300, category: 'Державна соціальна служба', services: 'Надання соціальних послуг, допомога ВПО', phone: '0487059000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'odesa_psych_support', name: 'Одеський кризовий психологічний центр', region: 'Odesa', address: 'м. Одеса, вул. Преображенська, 60', lat: 46.4810, lng: 30.7350, category: 'Психологічна підтримка', services: 'Психологічні консультації, групова підтримка', phone: '0971112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Lviv (additional)
  { id: 'lviv_legal_aid', name: 'Львівський центр безоплатної правової допомоги', region: 'Lviv', address: 'м. Львів, вул. Городоцька, 299', lat: 49.8300, lng: 23.9900, category: 'Юридична допомога', services: 'Безоплатна правова допомога, представництво в суді', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'lviv_psych_center', name: 'Центр психологічної підтримки "Родина" (Львів)', region: 'Lviv', address: 'м. Львів, вул. Пекарська, 69', lat: 49.8390, lng: 24.0400, category: 'Психологічна підтримка', services: 'Психологічні консультації для сім\'ї, дітей, ВПО', phone: '0951112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Kyiv (additional)
  { id: 'kyiv_legal_aid', name: 'Київський міський центр безоплатної правової допомоги', region: 'Kyiv', address: 'м. Київ, вул. Васильківська, 3', lat: 50.3990, lng: 30.4850, category: 'Юридична допомога', services: 'Безоплатна правова допомога, консультації', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'kyiv_psych_support', name: 'Київський міський центр психологічної допомоги', region: 'Kyiv', address: 'м. Київ, вул. Богдана Хмельницького, 30/10', lat: 50.4460, lng: 30.5150, category: 'Психологічна підтримка', services: 'Психологічні консультації, групи підтримки', phone: '0971112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'kyiv_disabled_center', name: 'Київський центр реабілітації осіб з інвалідністю', region: 'Kyiv', address: 'м. Київ, вул. Олени Теліги, 37', lat: 50.4800, lng: 30.4500, category: 'Соціальний захист', services: 'Реабілітація, допомога в адаптації', phone: '0441234567', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  // Kharkiv (additional)
  { id: 'kharkiv_legal_aid', name: 'Харківський центр безоплатної правової допомоги', region: 'Kharkiv', address: 'м. Харків, вул. Сумська, 106', lat: 50.0050, lng: 36.2300, category: 'Юридична допомога', services: 'Безоплатна правова допомога, консультації', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'kharkiv_psych_support', name: 'Харківський центр психологічної допомоги', region: 'Kharkiv', address: 'м. Харків, вул. Г. Сковороди, 12', lat: 49.9980, lng: 36.2250, category: 'Психологічна підтримка', services: 'Психологічні консультації, підтримка постраждалих від війни', phone: '0951112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'kharkiv_children_center', name: 'Харківський міський центр соціальних служб для сім\'ї, дітей та молоді', region: 'Kharkiv', address: 'м. Харків, пр. Науки, 17', lat: 50.0000, lng: 36.2200, category: 'Державна соціальна служба', services: 'Соціальний супровід, профілактика негативних явищ', phone: '0577000000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // Zaporizhzhia (additional)
  { id: 'zap_legal_aid', name: 'Запорізький центр безоплатної правової допомоги', region: 'Zaporizhzhia', address: 'м. Запоріжжя, пр. Соборний, 175', lat: 47.8495, lng: 35.1450, category: 'Юридична допомога', services: 'Безоплатна правова допомога, консультації', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'zap_psych_support', name: 'Запорізький центр психологічної допомоги', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Сталеварів, 18', lat: 47.8380, lng: 35.1350, category: 'Психологічна підтримка', services: 'Психологічні консультації, підтримка ВПО', phone: '0951112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'zap_children_fund', name: 'БФ "Діти Запоріжжя"', region: 'Zaporizhzhia', address: 'м. Запоріжжя, вул. Українська, 50', lat: 47.8280, lng: 35.1500, category: 'Благодійна організація', services: 'Допомога дітям, розвиваючі програми', phone: '0612123456', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // Zhytomyr (additional)
  { id: 'zhy_legal_aid', name: 'Житомирський центр безоплатної правової допомоги', region: 'Zhytomyr', address: 'м. Житомир, вул. Пушкінська, 44', lat: 50.2500, lng: 28.6650, category: 'Юридична допомога', services: 'Безоплатна правова допомога, консультації', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'zhy_psych_support', name: 'Житомирський центр психологічної допомоги', region: 'Zhytomyr', address: 'м. Житомир, вул. Михайлівська, 7', lat: 50.2530, lng: 28.6550, category: 'Психологічна підтримка', services: 'Психологічні консультації, групи підтримки', phone: '0951112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'zhy_children_fund', name: 'БФ "Діти Житомирщини"', region: 'Zhytomyr', address: 'м. Житомир, вул. Велика Бердичівська, 22', lat: 50.2480, lng: 28.6750, category: 'Благодійна організація', services: 'Допомога дітям з особливими потребами', phone: '0412123456', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

  // Dnipro (additional)
  { id: 'dnipro_legal_aid', name: 'Дніпровський центр безоплатної правової допомоги', region: 'Dnipro', address: 'м. Дніпро, пр. Дмитра Яворницького, 21', lat: 48.4630, lng: 35.0450, category: 'Юридична допомога', services: 'Безоплатна правова допомога, консультації', phone: '0800213103', email: '', status: 'Active', driveFolderUrl: '', budget: 0, website: 'https://legalaid.gov.ua/' },
  { id: 'dnipro_psych_support', name: 'Дніпровський центр психологічної допомоги', region: 'Dnipro', address: 'м. Дніпро, вул. Січеславська Набережна, 10', lat: 48.4600, lng: 35.0400, category: 'Психологічна підтримка', services: 'Психологічні консультації, підтримка ветеранів', phone: '0951112233', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },
  { id: 'dnipro_children_fund', name: 'БФ "Діти Дніпра"', region: 'Dnipro', address: 'м. Дніпро, вул. Воскресенська, 10', lat: 48.4700, lng: 35.0300, category: 'Благодійна організація', services: 'Допомога дітям-сиротам, дітям у складних життєвих обставинах', phone: '0567409000', email: '', status: 'Active', driveFolderUrl: '', budget: 0 },

];
